### ISSUE TITLE
Failed to open stream: phar error: "basic/config/web.php" is not a file in phar

### ISSUE THREAD

**Issue by wensenz** [box-project/box#1007]
$ ./basic-web.phar 
PHP Warning:  require(phar:///Users/zhongzhengwen/www/basic-web.phar/basic/web/../config/web.php): Failed to open stream: phar error: "basic/config/web.php" is not a file in phar "/Users/zhongzhengwen/www/basic-web.phar" in phar:///Users/zhongzhengwen/www/basic-web.phar/basic/web/index.php on line 10

system: macOs 13

i use  yii2 - basic project
```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
```

my box.json
```
{
    "alias": "basic-web.phar",
    "chmod": "0755",
    "directories": [
        "/Users/zhongzhengwen/www/basic/web"
    ],
    "finder": [
	    {
            "name": "*.php",
            "exclude": [
                "tests",
                "Tests"
            ],
            "in": "/Users/zhongzhengwen/www/basic/vendor"
        }
    ],
    "main": "/Users/zhongzhengwen/www/basic/web/index.php",
    "output": "basic-web.phar"
}
```

**Comment by theofidry** [comment]
Hi, unfortunately I cannot help out much with this issue as I get the error ` The file "/path/to/basic/index.php" does not exist.`.

Also just to make sure, but this is not to build a web app is it?

**Comment by theofidry** [comment]
Closing as lacking too much information.

If the problem still occur please feel free to open a new issue (but following the issue template please).
