### ISSUE TITLE
Piping the curl'ed phar results in fatal error

### ISSUE THREAD

**Issue by AlexSkrypnyk** [box-project/box#1125]
I have this issue with piping the installer created with box from curl to php

```bash
curl -SsL https://install.drevops.com/ | php
```

I'm getting the following error.

```
PHP Warning:  Phar::mapPhar(Standard input code): Failed to open stream: No such file or directory in Standard input code on line 16

Warning: Phar::mapPhar(Standard input code): Failed to open stream: No such file or directory in Standard input code on line 16
PHP Fatal error:  Uncaught PharException: unable to open phar for reading "Standard input code" in Standard input code:16
Stack trace:
#0 Standard input code(16): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in Standard input code on line 16

Fatal error: Uncaught PharException: unable to open phar for reading "Standard input code" in Standard input code:16
Stack trace:
#0 Standard input code(16): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in Standard input code on line 16
```

Downloading the file and running it with `php installer.php` works correctly.

Is there a way to prevent using of `require` inside of PHAR through config?

**Comment by theofidry** [comment]
Hi, apologies but I think there is some confusions.

>I have this issue with piping the installer created with box from curl to php

Box does not provide any installer. It is an idea yes #8, but it has not been implemented.

Having a look at `https://install.drevops.com/`, it looks like it provides the PHAR binary, which indeed cannot be piped like that. A PHAR is a PHP archive, i.e. in essence just a bunch of PHP files bundled together as a "ZIP". And to execute it you still need PHP

**Comment by AlexSkrypnyk** [comment]
@theofidry 
thank you for your reply

I did not mean the Box'es installer. 
> I have this issue with piping the installer **created with box** from curl to php

So, does this mean that any phar archive created with Box cannot be piped?

Is there any other way to combine PHP files into a single file so it can be piped?
