### ISSUE TITLE
Missing assets in the release 4.5.1

### ISSUE THREAD

**Issue by sereinity** [box-project/box#1161]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.5.1
| PHP version | NA
| Platform with version | NA
| Github Repo | NA

The release https://github.com/box-project/box/releases/tag/4.5.1 doesn't provide the release artifacts in assets. Other release do and it's still documented as a valid installation method in https://github.com/box-project/box/blob/main/doc/installation.md#github .

Not providing those items can break some users tools that will automatically ship those files (in my case `renovate`).

**Comment by theofidry** [comment]
Unfortunately it was because the pipeline failed due to API rate limiting. I restarted it the assets are now there
