### ISSUE TITLE
BOX info command is not always able to read the Requirement Checker section

### ISSUE THREAD

**Issue by llaville** [box-project/box#1235]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.5.1@1e10a1e 
| PHP version | 8.3.0
| Platform with version | Ubuntu 22.04 LTS on WSL2 with Docker
| Github Repo | - none

Trying to get `info` on some phar artifacts raise following **ErrorException** `Undefined array key "source"`

For example, with : 
- https://github.com/composer-unused/composer-unused/releases/download/0.8.11/composer-unused.phar built with Box v3.16
- https://github.com/llaville/umlwriter/releases/download/3.4.0/umlwriter.phar built with Box 4.3
- https://github.com/overtrue/phplint/releases/download/9.0.4/phplint.phar

## Composer Unused 0.8.11

<details>
 <summary>Output</summary>
 
 ```bash
 $ box info composer-unused.phar
 > output
API Version: 1.1.0

Built with Box: 3.16.0@adb282a

Archive Compression: None
Files Compression: None

Signature: SHA-1
Signature Hash: E11A7EE8E6670D53D3948E12BAE8392BE019BFC5

Metadata: None

Timestamp: 1701355209 (2023-11-30T14:40:09+00:00)

RequirementChecker:

In Requirement.php line 26:

  Undefined array key "source"


info [-l|--list] [-m|--mode MODE] [-d|--depth DEPTH] [--] [<phar>]
 ```
</details>

## UmlWriter 3.4.0

<details>
 <summary>Output</summary>
 
 ```bash
 $ box info umlwriter.phar
 > output
API Version: 1.1.0

Built with Box: 4.3.8@5534406

Archive Compression: None
Files Compression:
  - GZ (99.93%)
  - None (0.07%)

Signature: SHA-1
Signature Hash: B91733EBC7A4323262AD0191BD426C7833D1AA70

Metadata: None

Timestamp: 1681205957 (2023-04-11T09:39:17+00:00)

RequirementChecker:

In Requirement.php line 26:

  Undefined array key "source"


info [-l|--list] [-m|--mode MODE] [-d|--depth DEPTH] [--] [<phar>]
```
</details>

PS: I've noticed that box info command works when there are no Requirement Checker defined in project with box.json config file (like Phive or Composer)

Given on BOX info output

```
RequirementChecker: Not found.
```

**Comment by theofidry** [comment]
Should be part of 4.6.0 that has been released.
