### ISSUE TITLE
Secure your PHAR

### ISSUE THREAD

**Issue by theofidry** [box-project/box#15]
I'm not really familiar with the subject so this is more as a note if someone more of an expert can give his input and meanwhile doing some research.

From what I've seen so far:

- Signing your PHAR:
  - [Rob Peck blogpost](http://www.robpeck.com/2015/07/securely-signing-php-phar-files-with-openssl/#.WhxxfLSFiAw)
  - [Matthew Weier O'Phinney blogpost](https://mwop.net/blog/2015-12-14-secure-phar-automation.html)
- Singing a PHAR might not be enough: [Sucuri blogpost](https://blog.sucuri.net/2017/07/code-injection-in-phar-signed-php-archives.html). Might be worth checking [this](https://github.com/koto/phar-util#secure-remote-code-deployment-with-pharutil) as well.
- Investigate more

It would also be good to have an audit/review at some point by an actual expert.

**Comment by smoench** [comment]
For deptrac I decided to use only GPG itself. It works fine with phive/phar.io. Just add your public key to a keyserver and add the signature to github releases.

**Comment by theofidry** [comment]
I think so as well. I would actually like to go a bit further and:

- Add a deprecation notice/warning in the compilation/validation step with Box when signing the PHAR
- Add a GPG utility to allow Box to GPG sign the PHAR (but not using the PHAR built-in mechanism): https://github.com/humbug/box/issues/329

**Comment by smoench** [comment]
phar.io has a wrapper library for GnuPG https://packagist.org/packages/phar-io/gnupg. Might be interesting/reusable.

**Comment by theofidry** [comment]
There is now #329 for the GPG utility part. About how to secure your PHAR [a doc entry has been added](https://box-project.github.io/box/phar-signing/) which has been reviewed in #1096. 

A more in depth list of installation process has been added for [Box itself](https://github.com/box-project/box/blob/main/doc/installation.md#installation) which projects are free to take as a base.
