### ISSUE TITLE
Existing PHAR not removed

### ISSUE THREAD

**Issue by sergejostir** [box-project/box#456]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.8.3 
| PHP version | 7.2.24 
| Platform with version | Windows 10
| Github Repo | - 

I simply run the compile command with very baisc configuration and the previous PHAR doesn't get removed. It properly finds its path, but then says "The directory name is invalid." and nothing happens.

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\Json"
    ]
}

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
$ vendor/bin/box compile

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.8.3@43f13de

 // Loading the configuration file "C:\Users\User\project\box.json".

�🔨  Building the PHAR "C:/Users/User/project/wizard.phar"

? Removing the existing PHAR "C:/Users/User/project/wizard.phar"
The directory name is invalid.
? Registering compactors
  + KevinGH\Box\Compactor\Php
  + KevinGH\Box\Compactor\Json
? Adding main file: C:/Users/User/project/wizard
...
 ```
</details>

**Comment by theofidry** [comment]
this is curious... are the file system permissions ok? Is the file removable?

**Comment by sergiz** [comment]
I tried running the same set of files using the official composer docker container and it properly deleted the file beforehand.

Also I have just found out that on windows it includes a bunch of dependencies from require-dev, while on linux (in docker container) it does not. The compiled size on windows is 3,33MB and on linux 143KB ... Why is that so?

**Comment by theofidry** [comment]
No idea :/ Maybe some filters used only works on linux/osx. Since I don't have a Windows machine, I rather relied on windows users to find out and help out there

**Comment by sergiz** [comment]
I see, well I will run it through docker for now.

**Comment by theofidry** [comment]
Closing for now as unfortunately I do not have the bandwidth to attempt to fix it on Windows. I'll happily accept a PR to fix it however.
