### ISSUE TITLE
Why config/ gets excluded

### ISSUE THREAD

**Issue by sergejostir** [box-project/box#457]
Hello.

The documentation says that all files will be included, if you don't specify any of the options. Now I'm wondering why the config/ directory (which is in the project's root) gets excluded? The config folder has one .php file.

**Comment by theofidry** [comment]
Is that config file autoloaded in the `composer.json`?

**Comment by sergiz** [comment]
No, it's not.

**Comment by theofidry** [comment]
The you will have to add it manually :) Box can only infer information from the composer files, so sometimes it might need a help. Don't forget `force-autodiscovery: true` if you start adding files config but still want to leave the auto-discovery, cf. https://github.com/humbug/box/blob/master/doc/configuration.md#force-auto-discovery-force-autodiscovery

**Comment by sergiz** [comment]
Thanks. Already did all of that, I was just wondering, if I understood the documentation wrong.

> If you omit any of the following options, all the files found. The base directory used to find the files is either the configuration file if one is used/specified or the current working directory otherwise. 

I understand this, as that the box will include all files in the base directory (only excluding those that match the hardcoded patterns, eg. README). I guess it would be clearer, if it said that it will include all files that the composer.json refers to or something alike.

**Comment by theofidry** [comment]
Indeed, could you do a PR to clarify this?

**Comment by Jeckerson** [comment]
+1 to update the docs. Spent some time to figure why `vendor/` directories do not includes inside `.phar` when there are `directories` or `files` inside config file.
