### ISSUE TITLE
PHPUnit tests bug out when a --coverage option is used.

### ISSUE THREAD

**Issue by hopeseekr** [box-project/box#478]
The full bug report can be found at https://github.com/sebastianbergmann/phpunit/issues/4459.

This issue is to make you guys aware of it.

I mainly submitted this report because I hadn't seen this error in over 50,000+ PHP projects we've been able to run PHPUnit on to date.

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8 *and* 9.3.10 [latest]
| PHP version         | 7.2.33, 7.3.22, and 7.4.10 [latest]
| Installation Method | composer

## The Problem

As part of my Bettergist Collective project, I have been running phpunit (and a host of other utilities) against (eventually) the entire catalog of PHP packages in the Composer / Packagist.org universe. I currently maintain the PHP Packagist Archive, which already contains quarterly backups of every single package.

As such, I have run thousands and thousands of phpunits across tens of thousands of projects (currently ~50,000+), which (tell @sebastianbergmann !) is probably a better test suite of PHPUnit itself over anything on the planet (even more than what they must have!). I even test every package against PHPUnit 7.2 through 8.0 (if composer manages to install for each) ;_)

This is a new one for me. 

**I have never seen this in 23 years as a PHP developer and 20 year-user of PHPUnit, so that is why I'm reporting it.**

#### Current behavior

Tests run normally without any flags.
![image](https://user-images.githubusercontent.com/1125541/93643621-0327c400-f9c6-11ea-9965-f013f81dd3bd.png)

However, when any of the `--coverage` options is used, phpunit will report basically every test as "Risky".

![image](https://user-images.githubusercontent.com/1125541/93643893-7c271b80-f9c6-11ea-9e0b-c5d4177dbcf1.png)

#### How to reproduce

I discovered this when I got to the `h`s of PHP projects.

```bash
phpunit --coverage-text
```

It may very well have to do with arcane settings in their [**`phpunit.xml.dist`**](https://github.com/box-project/box/blob/master/phpunit.xml.dist):

```
         beStrictAboutChangesToGlobalState="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutResourceUsageDuringSmallTests="true"
         beStrictAboutCoversAnnotation="true"
```

I have never seen any of those out in the wild before...
#### Expected behavior

I would expect PHPUnit to run in a manner where tests are not marked as `Risky`, or otherwise fail, **just** because a `--coverage` option was used.

### Thank you!

I routinely use box to package phars, particularly for utiltiies used in my Bettergist Collective.

Cheers!

**Comment by owenvoke** [comment]
I think I understand what Sebastian is getting at. 🤔 Basically the test in [AnnotationDumperTest](https://github.com/box-project/box/blob/master/tests/Annotation/AnnotationDumperTest.php#L21) is only marked as covering `\KevinGH\Box\Annotation\AnnotationDumper`, however on line 50 it calls the `DocblockParser::parse()` method. Hence PHPUnit is throwing an error because it's being strict about the coverage as expected from the config. 👍🏻

Looks like the following diff can be applied to resolve this. 🤷🏻 However, this seems to apply in quite a few of the other tests. 🤔
```diff
diff --git a/tests/Annotation/AnnotationDumperTest.php b/tests/Annotation/AnnotationDumperTest.php
index 5772ff8..5b74f80 100644
--- a/tests/Annotation/AnnotationDumperTest.php
+++ b/tests/Annotation/AnnotationDumperTest.php
@@ -19,6 +19,7 @@ use PHPUnit\Framework\TestCase;

 /**
  * @covers \KevinGH\Box\Annotation\AnnotationDumper
+ * @covers \KevinGH\Box\Annotation\DocblockParser
  */
 class AnnotationDumperTest extends TestCase
 {
```

**Comment by owenvoke** [comment]
@theofidry, yeah. That probably makes more sense. 👍🏻

**Comment by villfa** [comment]
@hopeseekr the problem should be fix now. May you confirm it?

**Comment by jrfnl** [comment]
This looks to have been fixed. Should this issue be closed ?
