### ISSUE TITLE
Support PHP8

### ISSUE THREAD

**Issue by ptondereau** [box-project/box#486]
## Feature Request
Does it have any plan to support PHP8?
Do you think it should be OK with enabling PHP8.0 on CI and update composer.json?

**Comment by villfa** [comment]
Some dependencies don't support PHP-8 yet:

- https://github.com/beberlei/assert/issues/301
- https://github.com/paragonie/pharaoh/pull/14
- [PHP-Scoper](https://github.com/humbug/php-scoper)

Furthermore to run the tests with PHP-8 they must be compatible with PHPUnit 9.3.
Probably the best way to achieve that is to use *symfony/phpunit-bridge* (it is already a dependency but it is not used to run the tests).

**Comment by ptondereau** [comment]
https://github.com/beberlei/assert/pull/302

**Comment by smoench** [comment]
I started to add PHP 8 support for php-scoper https://github.com/humbug/php-scoper/pull/446

I think it would time to fork paragonie/pharaoh as it is not in active development nor getting feedback from the maintainers.

**Comment by villfa** [comment]
> I think it would time to fork paragonie/pharaoh as it is not in active development nor getting feedback from the maintainers.

@theofidry Since you're alone to maintain box and php-scoper I'm curious to know your opinion about that.

**Comment by villfa** [comment]
@smoench here: https://github.com/paragonie/pharaoh/releases/tag/v0.6.0

**Comment by smoench** [comment]
https://github.com/beberlei/assert/releases/tag/v3.3.0
