### ISSUE TITLE
Sign PHAR for PHIVE installation without --force-accept-unsigned

### ISSUE THREAD

**Issue by dbrekelmans** [box-project/box#487]
## Feature Request

If you sign the PHAR with a GPG signing key and attach the .asc file to the github release, the phive installation will no longer require the `--force-accept-unsigned` flag.

For detailed information on how to sign the PHAR, see: https://phar.io/howto/sign-and-upload-to-github.html

**Comment by szepeviktor** [comment]
This is very good idea. Future proof.

**Comment by danepowell** [comment]
#530 is an example of why we really need this. Without such a signature file, it's difficult for downstream CI systems to verify the integrity of box.phar.

**Comment by theofidry** [comment]
Will do for the next released, I uploaded my GPG key for Box.
