### ISSUE TITLE
box.phar missing from 3.9.0 release

### ISSUE THREAD

**Issue by GrahamCampbell** [box-project/box#490]

**Comment by smoench** [comment]
It's related to #488 as travis has failed to build the phar

**Comment by villfa** [comment]
@theofidry now that the main branch is stable, what is the best thing to do? Drop the 3.9.0 release before re-creating it, or make a 3.9.1 release?

**Comment by GrahamCampbell** [comment]
Probably 3.9.1?

**Comment by theofidry** [comment]
A new release: worst case I'll manually upload the missing PHARs

**Comment by greg0ire** [comment]
@theofidry can you manually upload 3.9.0 please? :pray:

**Comment by theofidry** [comment]
Uploaded. The version is not displayed correctly but the PHAR uploaded is based on the 3.9.0 tag

**Comment by greg0ire** [comment]
Thanks a lot!
