### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by villfa** [box-project/box#492]
## Feature Request

From https://docs.travis-ci.com/user/migrate/open-source-repository-migration 
>  travis-ci.org will be officially closed down completely no later than December 31st, 2020

It also explains why builds take more time:
> At peak usage times, you may see your build times are longer than they previously have been - we need to make sure all users have equal access to the .org platform until the end of the year as we move our infrastructure across to .com.

@theofidry I think you're the only one who have the rights in Travis to operate this migration.
FYI I did it for my own repositories in few minutes without modifying any code.

**Comment by theofidry** [comment]
This is good to know, I thought I already did this migration!

**Comment by owenvoke** [comment]
I guess this can now be closed as Box has moved to GitHub Actions. 👍🏻
