### ISSUE TITLE
"beberlei/assert" requires the extension "intl"

### ISSUE THREAD

**Issue by smoench** [box-project/box#516]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.11.0 
| PHP version | 8.0.0 
| Platform with version | php:8-cli-alpine (docker)
| Github Repo | - 

```bash
Step 8/19 : RUN php box.phar compile
 ---> Running in 5d5b954bc039

Box Requirements Checker
========================

> Using PHP 8.0.0
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  ...E....


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The package "beberlei/assert" requires the extension "intl". Enable it or
   install a polyfill.

```

I think we need to add https://github.com/symfony/polyfill-intl-icu as a box requirement.

**Comment by smoench** [comment]
Related to https://github.com/beberlei/assert/issues/309

**Comment by theofidry** [comment]
Hm I guess we can go with the polyfill to not have to rely on Assert? Since it's not too heavy (size-wise) I think it's ok

**Comment by villfa** [comment]
Perhaps we could consider moving to [webmozart/assert](https://github.com/webmozart/assert).
It doesn't require a specific extension and seems to have a larger community.

**Comment by theofidry** [comment]
That's also fine by me
