### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '_HumbugBox...\xxx' not found

### ISSUE THREAD

**Issue by cavo789** [box-project/box#518]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | Box version 3.11.0@b41ad52 2020-12-18 15:49:56 UTC (box.phar)
| PHP version | PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
| Platform with version | Windows
| Github Repo | https://github.com/cavo789/php-creating-phar 

Not sure it's a bug but I've search for the solution during hours.

I'm totally new to `box-project/box` and have created a small test on my disk. A very simple php script (*Hello World*) was OK but the script comes to errors as soon as I've added a composer vendor dependency.

No problem during the compile phase but well when calling my .phar file then.

```
PHP Fatal error:  Uncaught Error: Class '_HumbugBox91b0dcab05d9\Avonture\Classes\Glob' not found in phar://C:/Christophe/Repository/php-creating-phar/bin/test.phar/index.php:7
Stack trace:
#0 C:\Christophe\Repository\php-creating-phar\bin\test.phar(12): require()
#1 {main}
  thrown in phar://C:/Christophe/Repository/php-creating-phar/bin/test.phar/index.php on line 7
```

And I've solved this issue but removing `KevinGH\\Box\\Compactor\\PhpScoper,` in my `box.json` file.

Now, it works as expected. No idea if this is a normal behavior but, yes, at first sight, it was a bug for me (and it was difficult to find the solution so I post this message here for the next person with the same problem than me).

Have a nice day.

**Comment by theofidry** [comment]
The PHP-Scoper compactor is not enabled by default and it is mentioned [here](https://github.com/box-project/box/blob/master/doc/code-isolation.md#isolating-the-phar) that scoping _is_ a brittle process. I'm open to proposals to make it more obvious if you feel it's too hidden, but otherwise I don't know what can be done additionally here

**Comment by cavo789** [comment]
Hi Théo,

Thanks for the answer

I didn't have any solution, this is just my feedback. I'm a totally new user of Box (which is great!) and the first impression was, ouch!, it doesn't work well.

I've copy/pasted here and there what I've put in my `box.json` file so, yes, I've put there the PHP-Scoper compactor without knowing really his job and, most, his impact.

My experience of first user was not good at all and I've search hours to understand the origin of the problem.

If I need to mention some proposals, perhaps providing a `box.json` template file in your readme.md. 

Then, reading the list of issues and didn't find any issue mentionning the same problem I had.

I didn't give up trying though and kept looking, convinced that it was a mistake.

If my post here should serve a purpose, maybe it's fair to say that it would be a good idea, in your `readme.md`, to propose a step-by-step userguide for newcomers.

I just read the `Isolating the PHAR` paragraph: there is nothing there to alert the newcomer "Don't use it except you know what you're doing" or "If you get this error ... when running your phar file ... just remove the compactor ..."; something more "usable". Something I can retrieve by search for the error I've see in my console.

Once again, your project is great and thanks for it!

**Comment by theofidry** [comment]
>If I need to mention some proposals, perhaps providing a box.json template file in your readme.md.

Actually the issue might be there and I feel you went backwards because you started with a box.json from somewhere. There is no box.json template because by default you should not need one.

>If my post here should serve a purpose, maybe it's fair to say that it would be a good idea, in your readme.md, to propose a step-by-step userguide for newcomers.

Doesn't https://github.com/box-project/box#usage fit the bill?

>I just read the Isolating the PHAR paragraph: there is nothing there to alert the newcomer "Don't use it except you know what you're doing" or "If you get this error ... when running your phar file ... just remove the compactor ..."; something more "usable". Something I can retrieve by search for the error I've see in my console.

There is:

>Warning: keep in mind however that scoping is a very brittle process due to the nature of PHP. As such you will likely need some adjustments in your code or the configuration.

It feels like "Don't use it except you know what you're doing" is a bit too discouraging which is not the aim (IMO). That is not to say scoping is trivial, but ideally you want to do it
