### ISSUE TITLE
PHAR unusable due to the check-requirements setting

### ISSUE THREAD

**Issue by ajardin** [box-project/box#520]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.11.0
| PHP version | 7.4.x and 8.0.x
| Platform with version | macOS/Linux (not tested on Windows)
| Github Repo | - 

First of all I wanted to thank you for your work. I think it's a useful reminder when submitting an issue on the last day of the year... :smile:

It seems that the `check-requirements` setting is broken with the version **3.11.0** because of a missing file. Here is the error I receive when I try to execute my PHAR after the upgrade.
```
PHP Warning:  require(phar:///Users/XXXXX.phar/.box/vendor/composer/platform_check.php): Failed to open stream: phar error: ".box/vendor/composer/platform_check.php" is not a file in phar "/Users/XXXXX.phar" in phar:///Users/XXXXX.phar/.box/vendor/composer/autoload_real.php on line 25
```

At first glance, the regression has been introduced the last time the requirements checker has been dumped (https://github.com/box-project/box/commit/5e65d41dcd628473405be7c4aaa1f6d9784c9290#diff-db3a8dad6e56587fa883342c20ceee9918e2b68436fbb19a90636e86c281b8daR25). @muglug also seems to encounter the same problem according to his comment on the associated pull request (https://github.com/box-project/box/pull/515).

The file `.requirement-checker/vendor/composer/platform_check.php` is present when I dump the requirements checker locally, but its path is defined in the `.gitignore` file. Maybe we should remove this line and regenerate the dump?

**Comment by theofidry** [comment]
>The file .requirement-checker/vendor/composer/platform_check.php is present when I dump the requirements checker locally, but its path is defined in the .gitignore file. Maybe we should remove this line and regenerate the dump?

That is a solution indeed; Although I'm wondering if another solution is not to disable it for the requirement checker itself and when creating a PHAR with Box: it may (if you enable it with Composer 2, as it defaults to `php-only`) be entirely redundant but the Box requirement checker is slightly different:

- there is a guarantee of the order of execution as opposed to the Composer one which is only when the autoload is called
- unless you are using Composer 2 and have `platform-check` set to `true` the Box requirement checker does more
- the requirement checker still works regardless of whether you are using Composer 1, 2 or the Composer autoloader at all

**Comment by theofidry** [comment]
@smoench @villfa WDYT?

**Comment by villfa** [comment]
I agree that plateform-check is redundant with Box's requirement checker. It should be disabled.

On a side note it's annoying that no test detected the problem before.
