### ISSUE TITLE
Non-test Twig file is removed on phar compilation because naming looks like it it unit test (TwigTest.php)

### ISSUE THREAD

**Issue by jmalinens** [box-project/box#524]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.11.1
| PHP version | 7.4.6
| Platform with version | e.g. Ubuntu 20.04

This file should not be deleted on phar creation:
vendor/twig/twig/src/TwigTest.php

**Comment by theofidry** [comment]
Closing in favour of #525
