### ISSUE TITLE
Do not delete twig/twig/src/TwigTest.php on phar compilation

### ISSUE THREAD

**Issue by jmalinens** [box-project/box#525]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.11.1
| PHP version | 7.4.6
| Platform with version | e.g. Ubuntu 20.04

This file should not be deleted on phar creation:
vendor/twig/twig/src/TwigTest.php

it is probably deleted because it "looks like" a phpunit test file

**Comment by jmalinens** [comment]
solution for me now is adding this file in box.json

```json
{
  "files": [
    "vendor/twig/twig/src/TwigTest.php"
  ]
}

**Comment by theofidry** [comment]
If there is any way to prevent this in a reliable manner I'm open to it, but otherwise this looks like an acceptable trade-off as not removing `*Test.php` files is resulting in a lot of noise

**Comment by jmalinens** [comment]
I thought about creating an issue in twigphp/twig but it looks like too big of a BC break and hassle to rename the class there.
Let's just close this issue!
