### ISSUE TITLE
Compatibility with Composer v2.1.0 and later

### ISSUE THREAD

**Issue by ondrejmirtes** [box-project/box#555]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | Box version 3.11.1@83567c4 2021-01-02 09:53:51 UTC 
| PHP version | 8.0.3 
| Platform with version | e.g. Ubuntu/Windows/MacOS
| Github Repo | - 

Composer v2.1.0 started including `vendor/composer/installed.php` file in `InstalledVersions.php`. This file is new and isn't whitelisted by Box (or maybe PHP-Scoper) to be included in the final PHAR, leading to errors like:

```
PHP Fatal error:  require(): Failed opening required 'phar:///home/runner/work/phpstan/phpstan/extension/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/installed.php' (include_path='.:/usr/share/php') in phar:///home/runner/work/phpstan/phpstan/extension/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/InstalledVersions.php on line 319
```

**Comment by ondrejmirtes** [comment]
There was a similar problem before: https://github.com/box-project/box/pull/484

**Comment by theofidry** [comment]
Should be now working with 3.15
