### ISSUE TITLE
symfony/string's UnicodeString.php corrupt

### ISSUE THREAD

**Issue by kbond** [box-project/box#563]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.13.0@275b091
| PHP version | 7.4.18
| Platform with version | Ubuntu
| Github Repo | https://github.com/zenstruck/changelog

I'm getting an error when trying to run a phar that uses `symfony/string`. See details below. It's strange that it only occurs for one of my console commands. I believe the other console command calls the same code but no error... Removing the compactors in my `box.json.dist` does not fix the problem.

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "force-autodiscovery": true,
    "files": ["LICENSE", "README.md"],
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Json",
        "KevinGH\\Box\\Compactor\\Php"
    ]
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ changelog.phar self-update
  > PHP Warning:  include(phar:///home/runner/work/changelog/changelog/changelog/vendor/composer/../symfony/string/UnicodeString.php): failed to open stream: phar error: internal corruption of phar "/home/runner/work/changelog/changelog/changelog" (actual filesize mismatch on file "vendor/symfony/string/UnicodeString.php") in phar:///home/runner/work/changelog/changelog/changelog/.box/vendor/composer/ClassLoader.php on line 478
  > PHP Warning:  include(): Failed opening 'phar:///home/runner/work/changelog/changelog/changelog/vendor/composer/../symfony/string/UnicodeString.php' for inclusion (include_path='.:/usr/share/php') in phar:///home/runner/work/changelog/changelog/changelog/.box/vendor/composer/ClassLoader.php on line 478
  > PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\String\UnicodeString' not found in phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Helper/Helper.php:65
  > Stack trace:
  > #0 phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Style/SymfonyStyle.php(464): Symfony\Component\Console\Helper\Helper::width()
  > #1 phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Style/SymfonyStyle.php(67): > Symfony\Component\Console\Style\SymfonyStyle->createBlock()
  > #2 phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Style/SymfonyStyle.php(139): Symfony\Component\Console\Style\SymfonyStyle->block()
  > #3 phar:///home/runner/work/changelog/changelog/changelog/src/Command/SelfUpdateCommand.php(54): Symfony\Component\Console\Style\SymfonyStyle->success()
  > #4 phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Command/Command.php(299): Zenstruck\Changelog\Command\SelfUpdateCommand->execute()
  > #5 phar:///home/runner/work in phar:///home/runner/work/changelog/changelog/changelog/vendor/symfony/console/Helper/Helper.php on line 65
 ```
</details>

**Comment by theofidry** [comment]
This looks weird indeed; I see that you try a self-update command, if instead you pick the latest version and compile it is the resulting PHAR corrupted?

**Comment by kbond** [comment]
I'm now thinking what's happening is after the self update occurs (new file downloaded and swapped), there is some residual code that runs (in the same process) that tries to look for `UnicodeString` but it doesn't exist. self-update in the dev environment updates to the latest stable release (which doesn't include `symfony/string`). This would explain why I only see the problem with that command.

Hope that makes sense...?

What I'm going to try is to force-release a version that includes `symfony/string`, then try a self-update in my dev env.

**Comment by kbond** [comment]
Yep, looks like that was it. I removed code after the update occurs that would use `symfony/string` and it all worked as expected.

Don't believe this is a box issue, so I'm closing. Thanks for the help!
