### ISSUE TITLE
Using install-php-extensions instead of docker-php-ext-install

### ISSUE THREAD

**Issue by mlocati** [box-project/box#564]
## Feature Request

Installing PHP extensions inside official PHP docker images is not an easy task.
Indeed you need to:
- know the required apt (Debian) or apk (Alpine) system libraries
- know the system libraries needed to compile the PHP extensions, but that can be deleted after the compilation to save disk space

I created a (widely used) script that does all the above for a ton of extensions: see https://github.com/mlocati/docker-php-extension-installer.
For example, to install the gd PHP extension you only need to call `install-php-extensions gd`, without worrying about the system lbiraries.

**Comment by SamMousa** [comment]
According to the readme:

> ...For all those cases (unless you have a better way to handle it in which case PRs are welcomed) you will have to dirty your hands and tweak the Dockerfile to your needs.

I'm willing to implement this; it seems trivial enough. I use the script that @mlocati created in a lot of projects and I think it's the defacto standard for installing php extensions.


Note that even an existing docker file can be altered with just 1 line of code:
```docker
FROM php:8.1-cli-alpine
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/docker-php-ext-install
RUN chmod +x /usr/local/bin/docker-php-ext-install
RUN $(php -r '$extensionInstalled = array_map("strtolower", \get_loaded_extensions(false));$requiredExtensions = ["curl", "curl", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "json", "dom", "dom", "dom", "dom", "dom", "dom", "dom", "dom", "dom", "dom", "dom", "pdo", "pdo", "filter", "libxml", "libxml", "libxml", "hash", "mongodb", "tokenizer", "tokenizer", "tokenizer", "phar", "xmlwriter", "xmlwriter", "xmlwriter", "xmlwriter", "zip", "xml"];$extensionsToInstall = array_diff($requiredExtensions, $extensionInstalled);if ([] !== $extensionsToInstall) {echo \sprintf("docker-php-ext-install %s", implode(" ", $extensionsToInstall));}echo "echo \"No extensions\"";')

COPY codecept.phar /codecept.phar

ENTRYPOINT ["/codecept.phar"]
```
