### ISSUE TITLE
PHP 8.1: SerializablePhpScoper needs implementation of magic methods

### ISSUE THREAD

**Issue by jrfnl** [box-project/box#571]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | `master`
| PHP version | 8.1
| Platform with version | any
| Github Repo | - 

As of PHP 8.1, the PHP native [`Serializable` class is deprecated](https://wiki.php.net/rfc/phase_out_serializable).

Per the RFC:
>  A class is “only Serializable” if it is non-abstract, implements `Serializable`, and does not implement `__serialize()` and `__unserialize()`. > Then:
> * In PHP 8.1, declaring an “only Serializable” class will throw a deprecation warning. Other implementations of `Serializable` will be accepted without a deprecation warning, because libraries supporting PHP < 7.4 will generally need to implement both the old and new mechanisms.
> * In PHP 9.0 the `Serializable` interface will be removed and `unserialize()` will reject payloads using the C serialization format. Code needing to support both PHP < 7.4 and PHP >= 9.0 may polyfill the Serializable interface, though it will have no effect on serialization.
> 
> If a class implements both `Serializable` and `__serialize()`/`__unserialize()`, the latter take precedence (on versions that support them), and the `Serializable` interface is only used to decode existing serialization payload using the obsolete C format. To migrate to the new mechanism, it's possible to either replace Serializable entirely (if support for PHP 7.3 and below is not needed) or to implement both (if it is needed). 

The above has an impact on the `KevinGH\Box\PhpScoper\SerializablePhpScoper` class which implements `Serializable`.

I suspect this class can only be made compatible once the `Opis\Closure\SerializableClosure` class being (un)serialized has been made compatible with PHP 8.1 and the implementation used in that class is known.

Unfortunately, an initial attempt to make the `Opis\Closure\SerializableClosure` class compatible has bounced: https://github.com/opis/closure/pull/103 and it is unknown when a compatible version of the class will be available.

**Comment by jrfnl** [comment]
@theofidry I have no opinion on how to handle this, I just noticed the issue when running tests with Box and PHP 8.1 and figured it would be a good idea to write up the issue so the problem outline would be known.

**Comment by owenvoke** [comment]
@theofidry, related to https://github.com/box-project/box/issues/571#issuecomment-945869031, if we were to update to the Laravel Serializable Closure package (as done in [`owenvoke:feature/serializable-closure`](https://github.com/box-project/box/compare/master...owenvoke:feature/serializable-closure), it requires PHP 7.4 to unserialise closures. Would this be ok to bump to a minimum of PHP 7.4 in Box? 🤔 Or are you still wanting to maintain PHP 7.3 support? If not, I'll open that branch as a PR. 👍🏻 Only other thing that seems to use Opis Closure is [`amphp/parallel-functions`](https://github.com/amphp/parallel-functions)

**Comment by theofidry** [comment]
No I was planning to remove 7.3 from the supported versions so that’s fine
by me 👍

**Comment by theofidry** [comment]
Closed via #587
