### ISSUE TITLE
Satisfactory PHP version comparison fails

### ISSUE THREAD

**Issue by adamhopkinson** [box-project/box#574]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | Can't work out how to get this, as I'm using a package which I think pulls in a box phar... somewhere - but I've just installed it fresh today
| PHP version | 8.0.12
| Platform with version | MacOS 12.0.1 (tried on Intel & M1)
| Github Repo | - [https://github.com/hotmeteor/eco-cli](hotmeteor/eco-cli)

I'm trying to use Eco CLI, a package which manages Laravel .env values. It's built on Laravel Zero, which I believe uses box.

Running Eco for this first time should be as simple as `eco init` - but this gives:

```bash
Box Requirements Checker
========================

> Using PHP 8.0.12
> PHP is using the following php.ini file:
  /opt/homebrew/etc/php/8.0/php.ini

> Checking Box requirements:
  E................


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.3" or greater.
```

It looks to me like Box is correctly identifying PHP v8.0.12. 

Looking through the composer lock file, it looks like all the packages which require old versions are either both v7 and v8 (eg `^7.0 || 8.0`) or v7+ (eg `>=7.0`) (see below). When the warning says `version "^7.3" or greater`, the word 'greater' is confusing - does that mean `^7.3` or `>=7.3`?

I've read the [Requirements Checker](https://github.com/box-project/box/blob/master/doc/requirement-checker.md#requirements-checker) documentation and have managed to get Eco working (to some extent) by using the `BOX_REQUIREMENT_CHECKER=0` setting - but from that point I have further issues with Eco which I can't for sure say aren't related to this.

In terms of the chain of dependency here - particularly where Box is required and installed - I'm out of my depth.

### Steps to reproduce
```bash
mkdir eco-test && cd eco-test
composer require hotmeteor/eco-cli
./vendor/bin/eco init
```

### List of PHP version requirements from `composer.lock`
<details>
 <summary>I parsed out a full list of version requirements, sorted & de-duplicated:</summary>

```
>=5.3
>=5.3.0
>=5.3.3
>=5.4
>=5.5
>=5.6
>=7.0
>=7.0.0
>=7.1
>=7.2
>=7.2.0
>=7.2.5
>=7.3
^5.5.9 || ^7.0 || ^8.0
^7.0 || ^8.0
^7.1 || ^8.0
^7.1.3 || ^8.0
^7.1.8 || ^8.0
^7.2 || ^8.0
^7.2.5 || ^8.0
^7.2.5|^8.0
^7.2|^8.0
^7.3 || ^8
^7.3 || ^8.0
^7.3 || ~8.0.0 || ~8.1.0
^7.3|^8.0
^7.4|^8.0
~7.4.0 || ~8.0.0 || ~8.1.0
```

</details>

**Comment by theofidry** [comment]
Sorry it took so long to look at.

From what I can see, when you are installing the `hotmeteor/eco-cli`, `vendor/bin/eco` points to `vendor/hotmeteor/eco-cli/builds/eco`. I admit at this point I'm already a bit confused: there is packages providing a scoped PHAR, and it's there as a package just to allow an easy installation via Composer, for example PHPStan, but this one provides the scoped PHAR _and_ the source code. As weird as it looks and I don't quite understand the rationale, this is not the source of your problems.

Now looking at the problem itself, the requirement checker detects that you are on `8.0.12` and one of the constraint of the PHAR to be executed is `php: ^7.3`. This is were things are confusing. The way the requirement checker works is it dumps, at build time, all the requirement in the PHAR at `/.box/.requirements.php`. When you check the content of the eco PHAR, this file contains:

<details>

<summary>eco's PHAR .requirements.php</summary>

```
<?php

namespace _HumbugBox58fd4d9e2a25;

return array (
  0 => 
  array (
    'type' => 'php',
    'condition' => '^7.3',
    'message' => 'The application requires the version "^7.3" or greater.',
    'helpMessage' => 'The application requires the version "^7.3" or greater.',
  ),
  1 => 
  array (
    'type' => 'extension',
    'condition' => 'zlib',
    'message' => 'The application requires the extension "zlib". Enable it or install a polyfill.',
    'helpMessage' => 'The application requires the extension "zlib".',
  ),
  2 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The application requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The application requires the extension "json".',
  ),
  3 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "bitbucket/client" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "bitbucket/client" requires the extension "json".',
  ),
  4 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "guzzlehttp/guzzle" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "guzzlehttp/guzzle" requires the extension "json".',
  ),
  5 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "illuminate/support" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "illuminate/support" requires the extension "json".',
  ),
  6 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "laravel-zero/framework" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "laravel-zero/framework" requires the extension "json".',
  ),
  7 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "m4tthumphrey/php-gitlab-api" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "m4tthumphrey/php-gitlab-api" requires the extension "json".',
  ),
  8 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "nesbot/carbon" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "nesbot/carbon" requires the extension "json".',
  ),
  9 => 
  array (
    'type' => 'extension',
    'condition' => 'json',
    'message' => 'The package "ramsey/uuid" requires the extension "json". Enable it or install a polyfill.',
    'helpMessage' => 'The package "ramsey/uuid" requires the extension "json".',
  ),
  10 => 
  array (
    'type' => 'extension',
    'condition' => 'sodium',
    'message' => 'The application requires the extension "sodium". Enable it or install a polyfill.',
    'helpMessage' => 'The application requires the extension "sodium".',
  ),
  11 => 
  array (
    'type' => 'extension',
    'condition' => 'openssl',
    'message' => 'The package "composer/ca-bundle" requires the extension "openssl". Enable it or install a polyfill.',
    'helpMessage' => 'The package "composer/ca-bundle" requires the extension "openssl".',
  ),
  12 => 
  array (
    'type' => 'extension',
    'condition' => 'openssl',
    'message' => 'The package "padraic/humbug_get_contents" requires the extension "openssl". Enable it or install a polyfill.',
    'helpMessage' => 'The package "padraic/humbug_get_contents" requires the extension "openssl".',
  ),
  13 => 
  array (
    'type' => 'extension',
    'condition' => 'pcre',
    'message' => 'The package "composer/ca-bundle" requires the extension "pcre". Enable it or install a polyfill.',
    'helpMessage' => 'The package "composer/ca-bundle" requires the extension "pcre".',
  ),
  14 => 
  array (
    'type' => 'extension',
    'condition' => 'fileinfo',
    'message' => 'The package "league/flysystem" requires the extension "fileinfo". Enable it or install a polyfill.',
    'helpMessage' => 'The package "league/flysystem" requires the extension "fileinfo".',
  ),
  15 => 
  array (
    'type' => 'extension',
    'condition' => 'fileinfo',
    'message' => 'The package "league/mime-type-detection" requires the extension "fileinfo". Enable it or install a polyfill.',
    'helpMessage' => 'The package "league/mime-type-detection" requires the extension "fileinfo".',
  ),
  16 => 
  array (
    'type' => 'extension',
    'condition' => 'xml',
    'message' => 'The package "m4tthumphrey/php-gitlab-api" requires the extension "xml". Enable it or install a polyfill.',
    'helpMessage' => 'The package "m4tthumphrey/php-gitlab-api" requires the extension "xml".',
  ),
);
```

</details>

You can see the first condition is `^7.3` which is why you are getting the message you are currently having. Now looking at the _library_ composer.json, it is `"php": "^7.4|^8.0"`. To me this indicates the PHAR shipped is actually outdated with the source code.

I can't really do anything there, this is something that requires fixing in the eco package itself. I think it would really be best to keep the package being used as a regular package, and to provide the PHAR either add it to the package release or provide another package that contains _only_ the scoped PHAR.

<hr>

>When the warning says version "^7.3" or greater, the word 'greater' is confusing - does that mean ^7.3 or >=7.3?

The phrasing there is indeed not ideal this should be reworked. The actual check is that your PHP version does match the constraint given.
