### ISSUE TITLE
Scope of metadata producer by callback

### ISSUE THREAD

**Issue by llaville** [box-project/box#576]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.13.0@275b091
| PHP version | 7.4.25
| Platform with version | Ubuntu 18.04 LTS
| Github Repo | - https://github.com/llaville/php-compatinfo-db

<details>
 <summary>box.json.dist</summary>
 
 ```json
 {
    "alias": "compatinfo-db.phar",
    "directories": ["bin", "config", "src", "vendor"],
    "compression": "GZ",
    "main": "bin/compatinfo-db",
    "metadata": "Bartlett\\CompatInfoDb\\ComposerScripts::getPharMetadata"
 }
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ box compile
 > 
    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.13.0@275b091 2021-05-15 19:13:46 UTC

 // Loading the configuration file "/shared/backups/bartlett/php-compatinfo-db/box.json.dist".

🔨  Building the PHAR "/shared/backups/bartlett/php-compatinfo-db/bin/compatinfo-db.phar"

? Removing the existing PHAR "/shared/backups/bartlett/php-compatinfo-db/bin/compatinfo-db.phar"
? No compactor to register
? Adding main file: /shared/backups/bartlett/php-compatinfo-db/bin/compatinfo-db
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
    > 2371 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 3.13.0@275b091.
    >
    > @link https://github.com/humbug/box
? Setting metadata
  - Bartlett\CompatInfoDb\ComposerScripts::getPharMetadata
? Dumping the Composer autoloader
? Removing the Composer dump artefacts
? Compressing with the algorithm "GZ"
    > Warning: the extension "zlib" will now be required to execute the PHAR
? Setting file permissions to 0755
* Done.

No recommendation found.
No warning found.

 // PHAR: 2402 files (3.01MB)
 // You can inspect the generated PHAR with the "info" command.

 // Memory usage: 45.25MB (peak: 45.94MB), time: 5secs
 ```
</details>

One year later when I introduced the new feature #504 in version 3.10, I didn't realize that `box` scope was not the same as `compatinfo-db` scope, because I have implemented a `manifest` feature that read the PHAR metadata with a component that is of course in my project scope, and box did not know it !

Rather than see something like
```
? Setting metadata
  - array (
  0 => 'bartlett/php-compatinfo-db dev-master requires php ^7.2|^8.0 : 7.4.25',
  1 => 'bartlett/php-compatinfo-db dev-master requires ext-json * : 7.4.25',
  2 => 'bartlett/php-compatinfo-db dev-master requires ext-pcre * : 7.4.25',
  3 => 'bartlett/php-compatinfo-db dev-master requires ext-pdo * : 7.4.25',
  4 => 'bartlett/php-compatinfo-db dev-master requires ext-phar * : 7.4.25',
  5 => 'bartlett/php-compatinfo-db dev-master requires ext-spl * : 7.4.25',
  6 => 'bartlett/php-compatinfo-db dev-master requires composer/package-versions-deprecated ^1.8 : 1.11.99.4',
  7 => 'bartlett/php-compatinfo-db dev-master requires composer/semver ^1.0|^2.0|^3.0 : 3.2.6',
  8 => 'bartlett/php-compatinfo-db dev-master requires doctrine/orm ^2.7 : 2.10.2',
  9 => 'bartlett/php-compatinfo-db dev-master requires doctrine/dbal ^2.13.1||^3.1.1 : 3.1.4',
  10 => 'bartlett/php-compatinfo-db dev-master requires symfony/cache ^4.4|^5.0 : v5.3.10',
  11 => 'bartlett/php-compatinfo-db dev-master requires symfony/config ^4.4|^5.0 : v5.3.10',
  12 => 'bartlett/php-compatinfo-db dev-master requires symfony/console ^4.4|^5.0 : v5.3.10',
  13 => 'bartlett/php-compatinfo-db dev-master requires symfony/dependency-injection ^4.4|^5.0 : v5.3.10',
  14 => 'bartlett/php-compatinfo-db dev-master requires symfony/event-dispatcher ^4.4|^5.0 : v5.3.7',
  15 => 'bartlett/php-compatinfo-db dev-master requires symfony/finder ^4.4|^5.0 : v5.3.7',
  16 => 'bartlett/php-compatinfo-db dev-master requires symfony/messenger ^4.4|^5.0 : v5.3.10',
  17 => 'bartlett/php-compatinfo-db dev-master requires symfony/process ^4.4|^5.0 : v5.3.7',
  18 => 'bartlett/php-compatinfo-db dev-master requires symfony/requirements-checker ^2.0 : v2.0.0',
  19 => 'bartlett/php-compatinfo-db dev-master requires symfony/stopwatch ^4.4|^5.0 : v5.3.4',
  20 => 'bartlett/php-compatinfo-db dev-master requires (for development) composer/composer ^2.0 : 2.1.12',
  21 => 'bartlett/php-compatinfo-db dev-master requires (for development) psr/log ^1.0 : 1.1.4',
  22 => 'bartlett/php-compatinfo-db dev-master requires (for development) symfony/phpunit-bridge ^5.1 : v5.3.10',
)
```
We see only the callback name (see `output` report above)
```
? Setting metadata
  - Bartlett\CompatInfoDb\ComposerScripts::getPharMetadata
```

To fix this issue with `box compile` command, and probably other context, i'll propose a PR that add a `--bootstrap` option to `compile` command that let to specify whatever script we want to initialize context before compilation begin.

i.e, in my project situation: the `box-boostrap.php` file used with `--bootstrap` new option
```php
<?php
require_once __DIR__ . '/src/ComposerScripts.php';
```
See https://github.com/llaville/php-compatinfo-db/blob/master/src/ComposerScripts.php

**Comment by llaville** [comment]
In one of my project, I'd like to simplify the build metadata process

 "Build metadata for PHAR distribution without need of temporary cache file and trigger composer events" : it's now a success with https://github.com/llaville/php-compatinfo-db/commit/d20c8ef1066f29a428ca07c0889cd440e0008550

My box config file is : 
```
{
    "alias": "compatinfo-db.phar",
    "directories": ["bin", "config", "src", "vendor"],
    "compression": "GZ",
    "main": "bin/compatinfo-db",
    "metadata": "box-metadata.php"
}
```
And the `box-metadata.php` that is triggered only by `box compile` command (and no more by Composer events, as it was in previous version) is available at  https://github.com/llaville/php-compatinfo-db/blob/3.17/box-metadata.php

Box documentation that reflect this new box behavior is included in PR #582

**Comment by llaville** [comment]
Results in screenshots : 

Before patching box with PR 582, we have 

![box-314](https://user-images.githubusercontent.com/364342/147652449-255d0868-c7e7-4bb1-9348-9726505ff9d1.png)

![box-314-metadata](https://user-images.githubusercontent.com/364342/147652478-fdaf886b-c8ba-4a61-af43-6a53a08c972e.png)

Because filename (`box-metadata.php`) is proceed as a simple string

After patching box with PR 582, we will have

![box-314x](https://user-images.githubusercontent.com/364342/147652637-695b234f-79bd-4708-a7cf-0c91ea5a36dc.png)

![box-314x-metadata](https://user-images.githubusercontent.com/364342/147652657-29cbbec9-47b7-4472-9007-87eac616f30d.png)

I've now a real PHAR manifest included in `.phar` file

**Comment by theofidry** [comment]
Hi! Sorry for the detail and thanks for the PR.

I admit I'm not really familiar with PHAR metadatas... the usage seems a bit obscure to me and it's also not completely clear how much is really supported from it (and much less with the scoping process). So I think before pushing for anything else, it might be worth exploring what are the implications as right now there is very little testing about it in Box.

That being said, wouldn't your case work by moving the require statement within the callable?

**Comment by llaville** [comment]
> So I think before pushing for anything else, it might be worth exploring what are the implications as right now there is very little testing about it in Box.

@theofidry Thanks for reply. Scope to use the `metadata` box feature need at least a documentation update / explains.

Currently when users read https://github.com/box-project/box/blob/master/doc/configuration.md#metadata-metadata, and follow the steps they have no expected results.

- first (I've made an error in static function callable call)  Compare `"metadata": "MyCallbacks\\generateMetadata"` and `"metadata": "MyCallbacks::generateMetadata"`

- second the callable function must be autoloadable and it's not specified.

For example with `composer.json` 

```json
{
    "minimum-stability": "stable",
    "require": {
        "humbug/box": "^3.14"
    },
    "autoload": {
        "files": ["src/box-metadata.php"]
    }
}
```
With `src/box-metadata.php` contains the callable function

**Comment by llaville** [comment]
Oh, and yes there are no hurry, because I've already in mind another approach to handle manifest (with phar metadata), and have two other projects to finish first !

**Comment by theofidry** [comment]
I agree the documentation can definitely be improved. Part of the reason honestly is just the lack of usage of it in the wild. I find quite hard to image how practical it is to have to do something like:

```
$ php -r 'var_export((new Phar('/path/to/file.phar'))->getMetadata(), true);'
```

just to get that information (and what information it would be?). In practice with box it's a bit easier to consume via the `info` command, but I still honestly coudl'nt find a project where there was an _interesting_ metadata of some sorts.

So if you do have a concrete use case/demo I would be interested to know about it!

**Comment by llaville** [comment]
I should be able to provide you a use case in the beginning of next week.

**Comment by llaville** [comment]
@theofidry After a try on an alternative solution, I'm finally back to this project, especially since I found a solution to produce a Composer Manifest build on Box compilation for each user project (with the `metadata` config parameter).

Will propose you a solution (PR) in the next 2 days

**Comment by llaville** [comment]
@theofidry FYI: 
As this issue related to scope of callback may be fixed only to clarify the documentation, I'll create a PR in that way !

After, I'll open a new feature report follows by a PR to introduce the way to add a manifest into the metadata field of a PHAR when invoking the `box compile` command.
