### ISSUE TITLE
PHAR is missing for the 3.14.1 release

### ISSUE THREAD

**Issue by jakzal** [box-project/box#586]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.14.1
| PHP version | any
| Platform with version | any
| Github Repo | - 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/190447/148078665-719dcec8-3ec6-4887-b388-03b325e2d999.png">

It's there in 3.14.0:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/190447/148078712-49e25ae0-453c-4474-a1f6-dea2c9269fb5.png">

**Comment by SmetDenis** [comment]
Hey folks,

Do you have any news so far?

**Comment by theofidry** [comment]
Working on a new release which I'll make sure have the PHAR

**Comment by grasmash** [comment]
Ok thanks!

**Comment by jakzal** [comment]
3.15.0 has the jar attached 🥳  https://github.com/box-project/box/releases/tag/3.15.0

**Comment by jakzal** [comment]
Thank you @theofidry 🍺 

Your hard work has unblocked me big time: https://github.com/jakzal/phpqa/releases/tag/v1.66.0
