### ISSUE TITLE
Add a manifest from Composer data at compile time

### ISSUE THREAD

**Issue by llaville** [box-project/box#605]
## Feature Request

**Goal**
Add a manifest in any format (XML, TXT or other) in the metadata field of a PHAR when invoking the `box compile` command, and later to be able to read it easily with CLI command like 

```bash
php -r "var_export((new Phar('/path/to/application.phar'))->getMetadata());" 
```

Or with application by invoking the `application.phar --manifest`, and only to have to think to get the manifest from metadata field without to know where it was included in archive, like Phive did with [this code](https://github.com/phar-io/phive/blob/0.15.0/src/shared/phar/Phar.php#L69-L86)

See also https://www.php.net/manual/en/phar.getmetadata

**Principle**
Use the [metadata](https://github.com/box-project/box/blob/master/doc/configuration.md#metadata-metadata) box configuration parameter to define what instance of a class builder we will use to make the manifest.

Example **--1--** to build a simple TXT manifest with the following `box.json` declaration

```json
{
    "alias": "compatinfo-db.phar",
    "directories": ["bin", "config", "data", "src", "vendor"],
    "compression": "GZ",
    "metadata": "KevinGH\\Box\\Composer\\Manifest\\SimpleTextManifestBuilder"
}
```

What should we expect with (for example) project https://github.com/llaville/php-compatinfo-db

<details>
<summary>A simple preview</summary>

```
? Setting metadata
  - Using composer.json: /shared/backups/bartlett/php-compatinfo-db/composer.json
  - Using composer.lock: /shared/backups/bartlett/php-compatinfo-db/composer.lock
  - bartlett/php-compatinfo-db: 4.0.x-dev@ac18809
bartlett/graph-uml: 1.2.2
bartlett/php-compatinfo-db: dev-master
composer/semver: 3.2.7
cweagans/composer-patches: 1.7.2
doctrine/annotations: 1.13.2
doctrine/cache: 2.1.1
doctrine/collections: 1.6.8
doctrine/common: 3.2.2
doctrine/dbal: 3.3.1
doctrine/deprecations: v0.5.3
doctrine/event-manager: 1.1.1
doctrine/inflector: 2.0.4
doctrine/instantiator: 1.4.0
doctrine/lexer: 1.2.2
doctrine/orm: 2.11.1
doctrine/persistence: 2.3.0
graphp/graph: dev-master
graphp/graphviz: dev-master
psr/cache: 1.0.1
psr/container: 1.1.2
psr/event-dispatcher: 1.0.0
psr/log: 1.1.4
symfony/amqp-messenger: v5.4.3
symfony/cache: v5.4.3
symfony/cache-contracts: v2.5.0
symfony/config: v5.4.3
symfony/console: v5.4.3
symfony/dependency-injection: v5.4.3
symfony/deprecation-contracts: v2.5.0
symfony/doctrine-messenger: v5.4.3
symfony/event-dispatcher: v5.4.3
symfony/event-dispatcher-contracts: v2.5.0
symfony/filesystem: v5.4.3
symfony/finder: v5.4.3
symfony/messenger: v5.4.3
symfony/polyfill-ctype: v1.24.0
symfony/polyfill-intl-grapheme: v1.24.0
symfony/polyfill-intl-normalizer: v1.24.0
symfony/polyfill-mbstring: v1.24.0
symfony/polyfill-php72: v1.24.0
symfony/polyfill-php73: v1.24.0
symfony/polyfill-php80: v1.24.0
symfony/polyfill-php81: v1.24.0
symfony/process: v5.4.3
symfony/redis-messenger: v5.4.3
symfony/requirements-checker: v2.0.1
symfony/service-contracts: v2.5.0
symfony/stopwatch: v5.4.3
symfony/string: v5.4.3
symfony/var-exporter: v5.4.3
```

</details>

Example **--2--** to build a XML manifest with [phar-io/manifest](https://github.com/phar-io/manifest) package, and with the following `box.json` declaration

```json
{
    "alias": "compatinfo-db.phar",
    "directories": ["bin", "config", "data", "src", "vendor"],
    "compression": "GZ",
    "metadata": "KevinGH\\Box\\Composer\\Manifest\\PharIoManifestBuilder"
}
```

What should we expect with (for example) project https://github.com/llaville/php-compatinfo-db

<details>
<summary>A simple preview</summary>

```
? Setting metadata
  - Using composer.json: /shared/backups/bartlett/php-compatinfo-db/composer.json
  - Using composer.lock: /shared/backups/bartlett/php-compatinfo-db/composer.lock
  - <?xml version="1.0" encoding="UTF-8"?>
<phar xmlns="https://phar.io/xml/manifest/1.0">
    <contains name="bartlett/php-compatinfo-db" version="0.0.0-dev" type="library"/>
    <copyright>
        <author name="Laurent Laville" email="john.doe@example.com"/>
        <author name="Remi Collet" email="john.doe@example.com"/>
        <license type="BSD-3-Clause" url="https://spdx.org/licenses/BSD-3-Clause.html"/>
    </copyright>
    <requires>
        <php version="*"/>
    </requires>
    <bundles>
        <component name="bartlett/graph-uml" version="1.2.2"/>
        <component name="bartlett/php-compatinfo-db" version="0.0.0-dev"/>
        <component name="composer/semver" version="3.2.7"/>
        <component name="cweagans/composer-patches" version="1.7.2"/>
        <component name="doctrine/annotations" version="1.13.2"/>
        <component name="doctrine/cache" version="2.1.1"/>
        <component name="doctrine/collections" version="1.6.8"/>
        <component name="doctrine/common" version="3.2.2"/>
        <component name="doctrine/dbal" version="3.3.1"/>
        <component name="doctrine/deprecations" version="0.5.3"/>
        <component name="doctrine/event-manager" version="1.1.1"/>
        <component name="doctrine/inflector" version="2.0.4"/>
        <component name="doctrine/instantiator" version="1.4.0"/>
        <component name="doctrine/lexer" version="1.2.2"/>
        <component name="doctrine/orm" version="2.11.1"/>
        <component name="doctrine/persistence" version="2.3.0"/>
        <component name="graphp/graph" version="0.0.0-dev"/>
        <component name="graphp/graphviz" version="0.0.0-dev"/>
        <component name="psr/cache" version="1.0.1"/>
        <component name="psr/container" version="1.1.2"/>
        <component name="psr/event-dispatcher" version="1.0.0"/>
        <component name="psr/log" version="1.1.4"/>
        <component name="symfony/amqp-messenger" version="5.4.3"/>
        <component name="symfony/cache" version="5.4.3"/>
        <component name="symfony/cache-contracts" version="2.5.0"/>
        <component name="symfony/config" version="5.4.3"/>
        <component name="symfony/console" version="5.4.3"/>
        <component name="symfony/dependency-injection" version="5.4.3"/>
        <component name="symfony/deprecation-contracts" version="2.5.0"/>
        <component name="symfony/doctrine-messenger" version="5.4.3"/>
        <component name="symfony/event-dispatcher" version="5.4.3"/>
        <component name="symfony/event-dispatcher-contracts" version="2.5.0"/>
        <component name="symfony/filesystem" version="5.4.3"/>
        <component name="symfony/finder" version="5.4.3"/>
        <component name="symfony/messenger" version="5.4.3"/>
        <component name="symfony/polyfill-ctype" version="1.24.0"/>
        <component name="symfony/polyfill-intl-grapheme" version="1.24.0"/>
        <component name="symfony/polyfill-intl-normalizer" version="1.24.0"/>
        <component name="symfony/polyfill-mbstring" version="1.24.0"/>
        <component name="symfony/polyfill-php72" version="1.24.0"/>
        <component name="symfony/polyfill-php73" version="1.24.0"/>
        <component name="symfony/polyfill-php80" version="1.24.0"/>
        <component name="symfony/polyfill-php81" version="1.24.0"/>
        <component name="symfony/process" version="5.4.3"/>
        <component name="symfony/redis-messenger" version="5.4.3"/>
        <component name="symfony/requirements-checker" version="2.0.1"/>
        <component name="symfony/service-contracts" version="2.5.0"/>
        <component name="symfony/stopwatch" version="5.4.3"/>
        <component name="symfony/string" version="5.4.3"/>
        <component name="symfony/var-exporter" version="5.4.3"/>
    </bundles>
</phar>

```

</details>

You've to be aware that there are two potential issues with `phar-io/manifest` implementation (with workaround).

1. [Be able to create an Author without email](https://github.com/phar-io/manifest/issues/19)
2. [Branch version strings like dev-master are not supported](https://github.com/phar-io/version/issues/30)

Hope that @theseer will be able to fix it in future versions ;-)

And now, as promised @theofidry, the draft PR with prototype will follow. Code is already operational !

**Comment by llaville** [comment]
All feedbacks are welcome !

**Comment by llaville** [comment]
Another usage example with a custom manifest builder class (see https://github.com/llaville/php-compatinfo-db/commit/65f65ff2858a79680ba0c2721413e0851647bf75) that make such following results:

```
  - bartlett/php-compatinfo-db: 4.x-dev@3934e13
bartlett/php-compatinfo-db requires php ^7.4|^8.0: 7.4.27
bartlett/php-compatinfo-db requires ext-json *: 7.4.27
bartlett/php-compatinfo-db requires ext-pcre *: 7.4.27
bartlett/php-compatinfo-db requires ext-pdo *: 7.4.27
bartlett/php-compatinfo-db requires ext-phar *: 7.4.27
bartlett/php-compatinfo-db requires ext-spl *: 7.4.27
bartlett/php-compatinfo-db requires amphp/amp : v2.6.1
bartlett/php-compatinfo-db requires amphp/byte-stream : v1.8.1
bartlett/php-compatinfo-db requires amphp/parallel : v1.4.1
bartlett/php-compatinfo-db requires amphp/parallel-functions : v1.1.0
bartlett/php-compatinfo-db requires amphp/parser : v1.0.0
bartlett/php-compatinfo-db requires amphp/process : v1.1.3
bartlett/php-compatinfo-db requires amphp/serialization : v1.0.0
bartlett/php-compatinfo-db requires amphp/sync : v1.4.2
bartlett/php-compatinfo-db requires bartlett/graph-uml : 1.2.2
bartlett/php-compatinfo-db requires composer/package-versions-deprecated : 1.11.99.5
bartlett/php-compatinfo-db requires composer/pcre : 1.0.1
bartlett/php-compatinfo-db requires composer/semver ^3.0: 3.2.9
bartlett/php-compatinfo-db requires composer/xdebug-handler : 3.0.1
bartlett/php-compatinfo-db requires cweagans/composer-patches : 1.7.2
bartlett/php-compatinfo-db requires doctrine/annotations ^1.13: 1.13.2
bartlett/php-compatinfo-db requires doctrine/cache : 2.1.1
bartlett/php-compatinfo-db requires doctrine/collections : 1.6.8
bartlett/php-compatinfo-db requires doctrine/common : 3.2.2
bartlett/php-compatinfo-db requires doctrine/dbal ^3.2: 3.3.2
bartlett/php-compatinfo-db requires doctrine/deprecations : v0.5.3
bartlett/php-compatinfo-db requires doctrine/event-manager : 1.1.1
bartlett/php-compatinfo-db requires doctrine/inflector : 2.0.4
bartlett/php-compatinfo-db requires doctrine/instantiator : 1.4.0
bartlett/php-compatinfo-db requires doctrine/lexer : 1.2.2
bartlett/php-compatinfo-db requires doctrine/orm ^2.7: 2.11.1
bartlett/php-compatinfo-db requires doctrine/persistence : 2.3.0
bartlett/php-compatinfo-db requires fidry/console : 0.2.0
bartlett/php-compatinfo-db requires graphp/graph : dev-master
bartlett/php-compatinfo-db requires graphp/graphviz : dev-master
bartlett/php-compatinfo-db requires humbug/box : dev-build_manifest
bartlett/php-compatinfo-db requires humbug/php-scoper : 0.17.0
bartlett/php-compatinfo-db requires jetbrains/phpstorm-stubs : v2021.3
bartlett/php-compatinfo-db requires justinrainbow/json-schema : 5.2.11
bartlett/php-compatinfo-db requires laravel/serializable-closure : v1.1.0
bartlett/php-compatinfo-db requires nikic/iter : v2.2.0
bartlett/php-compatinfo-db requires nikic/php-parser : v4.13.2
bartlett/php-compatinfo-db requires paragonie/constant_time_encoding : v2.5.0
bartlett/php-compatinfo-db requires paragonie/pharaoh : v0.6.0
bartlett/php-compatinfo-db requires paragonie/random_compat : v9.99.100
bartlett/php-compatinfo-db requires paragonie/sodium_compat : v1.17.0
bartlett/php-compatinfo-db requires phpdocumentor/reflection-common : 2.2.0
bartlett/php-compatinfo-db requires phpdocumentor/reflection-docblock : 5.3.0
bartlett/php-compatinfo-db requires phpdocumentor/type-resolver : 1.6.0
bartlett/php-compatinfo-db requires psr/cache : 1.0.1
bartlett/php-compatinfo-db requires psr/container : 1.1.2
bartlett/php-compatinfo-db requires psr/event-dispatcher : 1.0.0
bartlett/php-compatinfo-db requires psr/log : 1.1.4
bartlett/php-compatinfo-db requires seld/jsonlint : 1.8.3
bartlett/php-compatinfo-db requires symfony/amqp-messenger : v5.4.3
bartlett/php-compatinfo-db requires symfony/cache ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/cache-contracts : v2.5.0
bartlett/php-compatinfo-db requires symfony/config ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/console ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/dependency-injection ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/deprecation-contracts : v2.5.0
bartlett/php-compatinfo-db requires symfony/doctrine-messenger : v5.4.3
bartlett/php-compatinfo-db requires symfony/event-dispatcher ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/event-dispatcher-contracts : v2.5.0
bartlett/php-compatinfo-db requires symfony/filesystem : v5.4.3
bartlett/php-compatinfo-db requires symfony/finder ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/messenger ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/polyfill-ctype : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-intl-grapheme : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-intl-normalizer : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-mbstring : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-php72 : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-php80 : v1.24.0
bartlett/php-compatinfo-db requires symfony/polyfill-php81 : v1.24.0
bartlett/php-compatinfo-db requires symfony/process ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/redis-messenger : v5.4.3
bartlett/php-compatinfo-db requires symfony/requirements-checker ^2.0: v2.0.1
bartlett/php-compatinfo-db requires symfony/service-contracts : v2.5.0
bartlett/php-compatinfo-db requires symfony/stopwatch ^4.4|^5.0: v5.4.3
bartlett/php-compatinfo-db requires symfony/string : v5.4.3
bartlett/php-compatinfo-db requires symfony/var-dumper : v5.4.3
bartlett/php-compatinfo-db requires symfony/var-exporter : v5.4.3
bartlett/php-compatinfo-db requires thecodingmachine/safe : v1.3.3
bartlett/php-compatinfo-db requires ulrichsg/getopt-php : v3.4.0
bartlett/php-compatinfo-db requires webmozart/assert : 1.10.0
bartlett/php-compatinfo-db requires webmozart/path-util : 2.3.0
```

**Comment by theofidry** [comment]
So if I understand correctly the idea would be to build a "manifest" which is basically a simplified version of a composer.lock?

To me it kind of begs the question of how manifest are being used in Phive: is it something built on Phive side or expected to be provided within the PHAR? Because apart from PHPUnit I could not see any which contain a `manifest.txt` file.

/cc @theseer

**Comment by llaville** [comment]
For me, it's the project leader that build a PHAR distribution who is responsible to write an XML manifest and include it in the root of code.

Here is a concrete example with [box.json.dist](https://github.com/bmitch/churn-php/blob/master/box.json.dist#L9) of the `bmitch/churn-php` application.

**Comment by llaville** [comment]
`bmitch/churn-php` suffer from the situation that the `manifest.xml` file is built manually and [included](https://github.com/bmitch/churn-php/blob/master/Makefile#L26) as I said above. 

See recent releases : 
- https://github.com/bmitch/churn-php/releases/tag/1.6.1
- https://github.com/bmitch/churn-php/releases/tag/1.6.0

**Comment by theseer** [comment]
> So if I understand correctly the idea would be to build a "manifest" which is basically a simplified version of a composer.lock?

Correct. And it can/will contain additional things that composer for valid reasons doesn't care about. For instance it can contain type specific details, e.g. in case of an extension the version range of the project it is am extension for.

> 
> It kind of begs the question of how manifest are being used in Phive: is it something built on Phive side or expected to be provided within the PHAR? Because apart from PHPUnit I could not see any which contain a `manifest.txt` file.

PHPUnit uses the a manifest currently for extensions (e.g. https://github.com/sebastianbergmann/phpunit-example-extension/blob/master/manifest.xml.in).

With PHPUnit 10 we're likely (hopefully ;) ) going to replace the text manifest with the same XML format.

With regards to phive: If a phar contains a phar-io style manifest, the details required `php/ext`-style things as well as the PHP version are checked (https://github.com/phar-io/phive/blob/master/src/services/phar/CompatibilityService.php#L43).

There will be more, e.g. we plan to use the `type` to allow for matching directories to be used for installation, e.g. an extension could be written to `./tools/{extesion-for}.d`, a `stub` type could be in `./stubs` ... 

Note: Currently, `phive` does not check via metadata but expects the manifest.xml file to be simply within the archive.

**Comment by theofidry** [comment]
>With PHPUnit 10 we're likely (hopefully ;) ) going to replace the text manifest with the same XML format.

In regards to #606, this makes me worried Box will always need to play catch-up with how to create the manifest and concerns of whether the created manifest can be understood by Phive/PHPUnit.

Given that this would likely depend on `phar-io/manifest` in any case would it be reasonable to expect the latter to provide a builder for the manifest?

>With regards to phive: If a phar contains a phar-io style manifest, the details required php/ext-style things as well as the PHP version are checked (https://github.com/phar-io/phive/blob/master/src/services/phar/CompatibilityService.php#L43).

In that regard it kinda makes it redundant with the PHAR shipped requirement checker, but I don't think it's a bad thing. IMO if there is anything to be done there would be to consider extracting those into a dedicated package to run the checker but I also don't know if it's really worth the effort.

>Note: Currently, phive does not check via metadata but expects the manifest.xml file to be simply within the archive.

Then maybe your issue should be approached differently @llaville. What about instead:

- Generate the manifest file within the compilation step (purely Box internal) – Since it's lightweight I don't think it's worth adding an option for it either
- Provide a built-in metadata factory to put as metadata the PHAR manifest content

Note that the last point is purely dependent on how you really want to use the manifest. Your proposed solution is indeed the best one _if_ you want to keep using the PHAR PHP base API. If you accept to rely on the Box `info` command, maybe a better way would be to add support for the manifest file there (i.e. add an entry: "manifest: <manifest content>")

**Comment by llaville** [comment]
> In regards to #606, this makes me worried Box will always need to play catch-up with how to create the manifest and concerns of whether the created manifest can be understood by Phive/PHPUnit.

If you're afraid about PHIVE compatibility, we can add few lines of code to add the `manifest.xml` file [expected by phive](https://github.com/phar-io/phive/blob/0.15.0/src/shared/phar/Phar.php#L69-L75)

```
diff --git a/src/Console/Command/Compile.php b/src/Console/Command/Compile.php
index cbe42c0..d415b56 100644
--- a/src/Console/Command/Compile.php
+++ b/src/Console/Command/Compile.php
@@ -572,6 +572,11 @@ HELP;
                     sprintf('Using manifest builder: %s', $metadata)
                 );
                 $metadata = ManifestFactory::create($config);
+
+                if (\is_string($metadata) && \substr($metadata, 0, 5) === '<?xml') {
+                    $box->addFile('manifest.xml', $metadata, true);
+                    $metadata = null;
+                }
             }

             $logger->log(
```

You can try by yourself to see what happens

Add into `box.json.dist` file of box-project itself the metadata setting like: 
```
"metadata": "KevinGH\\Box\\Composer\\Manifest\\PharIoManifestBuilder"
```

Then compile and verify contents

```bash
bin/box compile
bin/box extract bin/box.phar /tmp/box3
cat /tmp/box3/manifest.xml
```

chunk of contents
```
<?xml version="1.0" encoding="UTF-8"?>
<phar xmlns="https://phar.io/xml/manifest/1.0">
    <contains name="humbug/box" version="0.0.0-dev" type="library"/>
    <copyright>
        <author name="Kevin Herrera" email="john.doe@example.com"/>
        <author name="Théo Fidry" email="john.doe@example.com"/>
        <license type="MIT" url="https://spdx.org/licenses/MIT.html"/>
    </copyright>

```
There are some issues in `phar-io/manifest` (about email) and `phar-io/version` (package dev version). Hope @theseer will gave us a ROADMAP (answer)

Remember that `KevinGH\\Box\\Composer\\Manifest\\PharIoManifestBuilder` included into the PR is an attempt to write a compatible `phar-io/manifest` contents.

>> Note: Currently, phive does not check via metadata but expects the manifest.xml file to be simply within the archive.

Patch provided, will solve it !

> Then maybe your issue should be approached differently @llaville. What about instead:
>
>    Generate the manifest file within the compilation step (purely Box internal) – Since it's lightweight I don't think it's worth adding an option for it either
>    Provide a built-in metadata factory to put as metadata the PHAR manifest content

This is already was is done !

Perharps I did not well understood what you said/want

**Comment by theofidry** [comment]
Or maybe I had a too quick look ;) I'm a bit scattered as of late

**Comment by theseer** [comment]
> 
> > With PHPUnit 10 we're likely (hopefully ;) ) going to replace the text manifest with the same XML format.
> 
> In regards to #606, this makes me worried Box will always need to play catch-up with how to create the manifest and concerns of whether the created manifest can be understood by Phive/PHPUnit.

While there is of course a chance that the manifest xml respentation has to evolve over time, we didn't need to modify the format since its invention. We will, however, have to add the new type `stub` as the current implementation only has `library`, `application` and `extension`. That will be a BC compliant change though as this is merely a new type without any other changes for other types or the structure. 

> 
> Given that this would likely depend on `phar-io/manifest` in any case would it be reasonable to expect the latter to provide a builder for the manifest?

I'm not sure what exactly you envision when speaking of a "builder". In `phar-io/manifest` we do have an object graph, representing the actual manifest and its data. The repository contains code to re-create that object graph from the XML serialization format as well as a Serializer to dump said graph to XML.

I already suggested to @llaville at some point that we could create a new project under the phar-io umbrella to have a "composer-to-manifest" kind of thing. There would be a few things though that have to get provided by some means as composer doesn't know/deal with them. E.g. while the type could probably be mapped to some extend from the composer configuration, the target application for an extension as well as the version constraint won't be found there - as far as I know at least. 

Other than that, the Manifest is a rather plain set of PHP classes. It just happens to be expected to have been serialized to an XML document. 

Not sure if that answers your question?


> 
> > With regards to phive: If a phar contains a phar-io style manifest, the details required like php/ext-style things as well as the PHP version are checked ([phar-io/phive@`master`/src/services/phar/CompatibilityService.php#L43](https://github.com/phar-io/phive/blob/master/src/services/phar/CompatibilityService.php?rgh-link-date=2022-02-14T12%3A02%3A30Z#L43)).
> 
> In that regard it kinda makes it redundant with the PHAR shipped requirement checker, but I don't think it's a bad thing. IMO if there is anything to be done there would be to consider extracting those into a dedicated package to run the checker but I also don't know if it's really worth the effort.

The basics, e.g. PHP version as well as extensions is only a few lines of code once the manifest data is available as object graph. I'm not sure if an independent project would save much - except that we  could share that implementation I cannot see any benefits. 

The bigger problems start when we have to actually do dependency resolving, e.g. when a set of extensions need to match a target application, taking all the respective version constraints into account. But that's a different and unrelated issue..

> 
> > Note: Currently, phive does not check via metadata but expects the manifest.xml file to be simply within the archive.
> 
> Then maybe your issue should be approached differently @llaville. 

Just for the record: We  *could* change that for a future version of phive and have it look at the metadata as well. Not sure if that would be any better as it makes generating the phar archive a bit more complex as but as you already have code in box to do that,... The Manifest classes should also serialize well as they are immutable pure DTOs.

> 
>     * Generate the manifest file within the compilation step (purely Box internal) – Since it's lightweight I don't think it's worth adding an option for it either
> 
>     * Provide a built-in metadata factory to put as metadata the PHAR manifest content
> 
> 
> Note that the last point is purely dependent on how you really want to use the manifest. Your proposed solution is indeed the best one _if_ you want to keep using the PHAR PHP base API. If you accept to rely on the Box `info` command, maybe a better way would be to add support for the manifest file there (i.e. add an entry: "manifest: ")

Whatever solution is picked, we should probably ensure that we align things so `phive` can make use of it. I don't have any issues adding code to `phive` to do that, if it would be needed.

**Comment by llaville** [comment]
As it seems too much (complicated) for audience, I propose to let down this feature, and only to pass contextual parameters that will allow to everyone to do what they want.

@theofidry Are you agree for a PR with just this change 

```
diff --git a/src/Console/Command/Compile.php b/src/Console/Command/Compile.php
index ebc1ee6..73e8b62 100644
--- a/src/Console/Command/Compile.php
+++ b/src/Console/Command/Compile.php
@@ -546,7 +546,7 @@ HELP;
             );

             if (is_callable($metadata)) {
-                $metadata = $metadata();
+                $metadata = $metadata($config, $box);
             }

             $logger->log(
```

**Comment by llaville** [comment]
Closes this feature, because I'm working on a standalone project !

**Comment by theofidry** [comment]
@llaville is that definitive? Because it feels like a nice to have to automatically add a manifest file to Box itself

**Comment by llaville** [comment]
> @llaville While it would be nice for the `phar-io/manifest` to be used, I don't really have an issue if you create your own implementation. 

Thanks

> The only thing that counts is that the resulting xml representation complies to the [manifest.xsd](https://github.com/phar-io/manifest/blob/master/manifest.xsd). (Note: the manifest.xsd will be available soon on a non-repository url as soon as I managed to get some more strictness defined on values)

I've a question about namespace : 
As I've my own implementation that is compatible with `phar-io/manifest` 2.0.x, I've specified a new version (1.1) that may cause an issue with your manifest.xsd
```<phar xmlns="https://phar.io/xml/manifest/1.1">```

The reason of this new version 1.1 is : I've added an optional `constraint` attribute on `bundles/component` tag.

That is usefull to distinguish implicitly vs explicitly packages installed. When constraint is not empty => package implicitly installed (constraint is pick from composer.json)

Example from my CI unit tests / fixtures : https://github.com/llaville/box-manifest/blob/master/tests/fixtures/phario-manifest-2.0.x-dev/manifest.xml
And unit test case : https://github.com/llaville/box-manifest/blob/master/tests/ManifestFactoryTest.php#L84-L99

@theseer What do you think about this change ?

**Comment by llaville** [comment]
@theseer  Other issue with current version of your `manifest.xsd` https://github.com/phar-io/manifest/blob/9c31f71fa0c993ab2e86ad31f5ef66066e3d368f/manifest.xsd#L41 :  
Composer license may be multiple https://github.com/composer/composer/blob/2.2/res/composer-schema.json#L16

**Comment by llaville** [comment]
@theseer Other issue with https://github.com/phar-io/manifest/blob/9c31f71fa0c993ab2e86ad31f5ef66066e3d368f/manifest.xsd#L62 and Composer compatibility (license url is optional)

**Comment by theseer** [comment]
> > @llaville While it would be nice for the `phar-io/manifest` to be used, I don't really have an issue if you create your own implementation.
> 
> Thanks
> 
> > The only thing that counts is that the resulting xml representation complies to the [manifest.xsd](https://github.com/phar-io/manifest/blob/master/manifest.xsd?rgh-link-date=2022-02-18T10%3A29%3A36Z). (Note: the manifest.xsd will be available soon on a non-repository url as soon as I managed to get some more strictness defined on values)
> 
> I've a question about namespace : As I've my own implementation that is compatible with `phar-io/manifest` 2.0.x, I've specified a new version (1.1) that may cause an issue with your manifest.xsd `<phar xmlns="https://phar.io/xml/manifest/1.1">`
> 
> The reason of this new version 1.1 is : I've added an optional `constraint` attribute on `bundles/component` tag.
> 
> That is usefull to distinguish implicitly vs explicitly packages installed. When constraint is not empty => package implicitly installed (constraint is pick from composer.json)

> @theseer What do you think about this change ?

To be quite frank: That's broken and a bad idea for various reasons:
- You're hijacking our namespace with an incompatible extension that will break as soon as we might release an updated manifest
- I don't see any benefit of having a constraint information within the phar. All we care about - from the manifest's point of view - is what *is* bundled in the archive, not what would have potentially been possible.
- I also don't see how extending the manifest with information we don't support would help anyone?

**Comment by llaville** [comment]
Finally I've solved the namespace and other compatibility issues (notified).

I've wrote a new specialized builder (`PharIoManifestBuilder`) based on current [SimpleXmlManifestBuilder](https://github.com/llaville/box-manifest/blob/master/src/Composer/Manifest/SimpleXmlManifestBuilder.php) that honor your current `manifest.xsd` (and if it evolved, I may apply change easily without to break the `SimpleXmlManifestBuilder`

I'll push the code in few minutes now !

**Comment by llaville** [comment]
New code is online with commit https://github.com/llaville/box-manifest/commit/66e35d4742dbd1c0bf97dd8fab3c573a85319990

FYI: a new entry to the factory to produce a compatible `phar-io/manifest` xml that honor the xsd.
```json
{
    "metadata": "Bartlett\\BoxManifest\\Composer\\ManifestFactory::toPharIo"
}
```
And of course keep previous XML implementation with `Bartlett\\BoxManifest\\Composer\\ManifestFactory::toXml`

**Comment by theseer** [comment]
@llaville Can you please __not__ hijack our namespace with a proprietary format? I do not have any issues with your application creating not using our code to create an xml manifest or you defining your own xml format. You are, of course, free to create a custom implementation that generates "our" xml format. __But do not use our namespace and domain for a proprietary format__.

_As a side note_: I fail to see the purpose of having a proprietary xml format when there is already a somewhat established one. The manifest data within a phar is invisible to the regular user unless some code makes use of it. Phive will not parse your proprietary format, PHPUnit will not parse  your proprietary format. What's the purpose? Maybe I'm missing something obvious?

**Comment by llaville** [comment]
@theseer I'll drop support of `phar-io/manifest` format, even with my implementation. All reasons [were given](https://github.com/llaville/box-manifest/discussions/1) in my project discussion forum.

@theofidry Finally, after many attempt to try to contribute for a cool feature, I'll continue to work on my side with my standalone version with TEXT format only !
