### ISSUE TITLE
Question or Bug about `box info --metadata` command

### ISSUE THREAD

**Issue by llaville** [box-project/box#612]
Option `metatada` of the `box info` command seems useless, because when a PHP Archive has some meta-data, there are displayed without the need to specify option `--metadata`

**Context**
Official version
```
Box version 3.16.0@adb282a 2022-02-13 23:54:13 UTC
```

**Comment by theofidry** [comment]
Yes it looks like the option is not used at all.

I would expect it to just dump the metadata bare (i.e. without any of the formatting that may be present in the regular box info) but maybe it can simply be removed for now.
