### ISSUE TITLE
Class/namespace not found for package required via composer

### ISSUE THREAD

**Issue by bilogic** [box-project/box#620]
I'm using Laravel-zero which relies on this project to build PHARs, https://laravel-zero.com/docs/build-a-standalone-application.

After it compiles a PHAR using `box-project/box`, it reports not being able to find one of the classes I required via composer. I went through `box-project/box`'s docs, but can't seem to find how I can include packages found inside `vendor/`. 

Any idea? Thank you.

**Comment by theofidry** [comment]
Hi, yes there is several things:

- you can inspect the PHAR itself to see if it's as you expect it to be
- you can also extract the PHAR into a directory `$ box extract --help` to inspect it
- you can check the config doc: https://github.com/box-project/box/blob/master/doc/configuration.md#including-files

Without more info that's all I can offer you unfortunately.

**Comment by bilogic** [comment]
My package is symlinked in `vendor/` by `composer` as it is specified in `repositories` of `composer.json`. Is this something that box can handle?

**Comment by bilogic** [comment]
Ok, I found the issue, symlinked packages are not included in the PHAR. 
Is this by design? If not, can it be fixed? If yes, can `box` be upgraded to handle them?

Once I forced `composer` to copy instead of symlink, the compile PHAR now includes my package.
```JSON
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "symlink": false
            }
        }
    ]
}
```

**Comment by theofidry** [comment]
AFAICR it's not supported only because no one had the need for it and/or the will to add support for it.

I can't remember if it was supported when I took over the project, but I remember explicitly removing support for it (it wasn't clear if it was working or not before) as it allowed to cut down on the number of things to test.
