### ISSUE TITLE
Docker support with PHP 8

### ISSUE THREAD

**Issue by llaville** [box-project/box#630]
As latest version 3.16.0, Box is supposed to support both PHP 7.x and 8.x

But when you look inside [DockerFileGenerator](https://github.com/box-project/box/blob/3.16.0/src/DockerFileGenerator.php#L43-L49) no images are defined for PHP 8.0 and 8.1

Is it just forgotten ? `8.0-cli-alpine` and `8.1-cli-alpine` images are available on DockerHub

**Comment by theofidry** [comment]
I think so yes 😅
