### ISSUE TITLE
Symfony function polyfills get put into the wrong namespace

### ISSUE THREAD

**Issue by allejo** [box-project/box#657]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.16.0
| PHP version | 7.4.21
| Platform with version | macOS
| Github Repo | [allejo/rrlog @ `feature/box-cleanup`](https://github.com/allejo/rrlog/tree/feature/box-cleanup) 

When my `box.json.dist` uses the `"KevinGH\\Box\\Compactor\\PhpScoper"` compactor, any function that Symfony polyfills in the global namespace is written into the wrong namespace. Kinda hard to explain, so let me try my best.

In my project's `vendor` directory, the `InputOption.php` file makes use of `str_starts_with`, which exists in PHP 8.0+ but Symfony makes use of `symfony/polyfills-php80` to polyfill this function, allowing it to work as intended.

```php
namespace Symfony\Component\Console\Input;

class InputOption
{
    // ...

    public function __construct(string $name, $shortcut = null, int $mode = null, string $description = '', $default = null)
    {
        if (str_starts_with($name, '--')) {
            $name = substr($name, 2);
        }

// ...
```

This works because `symfony/polyfills-php80` has a bootstrap file that has this logic in the global namespace:

```php
if (!function_exists('str_starts_with')) {
    function str_starts_with(?string $haystack, ?string $needle): bool { ... }
}
```

After running Box with PhpScoper, the `InputOption.php` file ends up with code that looks like,

```php
namespace humbug12345\Symfony\Component\Console\Input;

class InputOption
{
    // ...

    public function __construct(string $name, $shortcut = null, int $mode = null, string $description = '', $default = null)
    {
        if (\str_starts_with($name, '--')) { // <- Notice the `\` at the beginning of `str_starts_with()`
            $name = substr($name, 2);
        }

// ...
```

And `symfony/polyfill-php80`'s bootstrap file has been updated to,

```php
namespace humbug12345;

if (!function_exists('str_starts_with')) {
    function str_starts_with(?string $haystack, ?string $needle): bool { ... }
}
```

This leads to the `str_starts_with()` not being found since `InputOption.php` is referencing the one in the global namespace and the polyfill is being added to the scoped namespace.

<details>
 <summary>box.json.dist</summary>
 
 ```json
 {
    "main": "bin/rrlog",
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\PhpScoper"
    ],
    "datetime": "release-date",
    "git-version": "package_version",
    "output": "rrlog.phar"
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
$ php -d display_errors=on rrlog.phar

Fatal error: Uncaught Error: Call to undefined function str_starts_with() in phar:///Users/allejo/Development/BZFlag/rrlog/rrlog.phar/vendor/symfony/console/Input/InputOption.php on line 20

Error: Call to undefined function str_starts_with() in phar:///Users/allejo/Development/BZFlag/rrlog/rrlog.phar/vendor/symfony/console/Input/InputOption.php on line 20
 ```
</details>

**Comment by Luc45** [comment]
There are a lot of libraries with this issue out there. The way that Box itself handles is by skip scoping the polyfills. Essentially, use this `scoper.inc.php`:

```php
<?php

use Isolated\Symfony\Component\Finder\Finder;

$polyfillsBootstraps = \array_map(
	function ( SplFileInfo $fileInfo ) {
		return $fileInfo->getPathname();
	},
	\iterator_to_array(
		Finder::create()
		      ->files()
		      ->in( __DIR__ . '/vendor/symfony/polyfill-*' )
		      ->name( 'bootstrap.php' ),
		false,
	),
);

$polyfillsStubs = [];
try {
	$polyfillsStubs = \array_map(
		function ( SplFileInfo $fileInfo ) {
			return $fileInfo->getPathname();
		},
		\iterator_to_array(
			Finder::create()
			      ->files()
			      ->in( __DIR__ . '/vendor/symfony/polyfill-*/Resources/stubs' )
			      ->name( '*.php' ),
			false,
		),
	);
} catch ( Throwable $e ) {
	// There may not be any stubs?
}

return [
	'exclude-namespaces' => [
		'Symfony\Polyfill'
	],
	'exclude-files' => \array_merge( $polyfillsBootstraps, $polyfillsStubs ),
];
```

It seems to me that this opens a breach in the encapsulation of the Phar, but it's the only solution that I could find.

**Comment by theofidry** [comment]
To expand on @Luc45 good explanation, there is this doc entry https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#polyfills.

Of course could be missing in which case contributions are welcomed.

I'm also aware this is a PITA, no one is happy about it, but maybe I found a way to get rid of that in the next version.
