### ISSUE TITLE
provide official docker images for box

### ISSUE THREAD

**Issue by BigBadBassMan** [box-project/box#693]
## Feature Request

Since more and more projects adopt docker (for CI/CD or simply for build purposes), an official box docker-image (or collection of images for different supported PHP versions), available from hub.docker.com, would be beneficial.

These could be built and pushed by Github actions on each release.

**Comment by theofidry** [comment]
I'm happy to merge it if there is an easy way to update the image on the docker hub on release 👍

**Comment by BigBadBassMan** [comment]
> I'm happy to merge it if there is an easy way to update the image on the docker hub on release +1

I'm trying to figure this out, the idea was that a release package triggers a docker action which builds and publishes the image.

May take awhile since I have not used Github Actions before.

**Comment by theofidry** [comment]
>It will run even on branches/pr's but still use only official packages, though.

Can't it depend on the `Build.publish-phar` job to alleviate that issue?

>docker "latest" is automatically assigned to each new built image - this may lead to problems, when releasing both 4.x and 3.x versions...

Maybe this could be solved by using a different image name? E.g. box3 & box4.
