### ISSUE TITLE
Enum file is not copying 

### ISSUE THREAD

**Issue by sivajik34** [box-project/box#722]
Symfony console AnsicolorMode enum file is not copying

**Comment by sivajik34** [comment]
PHP Fatal error: Uncaught Error: Class "Symfony\Component\Console\Output\AnsiColorMode" not found in phar:/vendor/symfony/console/Terminal.php:18

**Comment by glo45343** [comment]
![image](https://user-images.githubusercontent.com/95923922/206827730-50b68abe-3c58-4d47-afd4-1f5988e83081.png)

**Comment by glo45343** [comment]
[debug] Current memory limit: "-1"
[debug] Checking BOX_ALLOW_XDEBUG
[debug] phar.readonly is enabled
[debug] The Xdebug extension is loaded (3.1.5) xdebug.mode=develop
[debug] Configured `phar.readonly=0`
[debug] Process restarting (BOX_ALLOW_XDEBUG=internal|3.1.5|1|*|*)
[debug] Running /usr/bin/php8.1 /home/siva/Downloads/box.phar compile -vvv
[debug] Current memory limit: "-1"
[debug] Checking BOX_ALLOW_XDEBUG
[debug] Restarted (167 ms). The Xdebug extension is not loaded

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 4.2.0@afc3a47 2022-11-21 22:20:19 UTC

 // Loading the configuration file "/home/siva/con/myapp/box.json".                                                     

🔨  Building the PHAR "/home/siva/con/myapp/mptt.phar"

? Removing the existing PHAR "/home/siva/con/myapp/mptt.phar"
[debug] Increased the maximum number of open file descriptors from ("1024", "1048576") to ("2176", "unlimited")
? Registering compactors
  + KevinGH\Box\Compactor\Php
  + KevinGH\Box\Compactor\Json
? Adding main file: /home/siva/con/myapp/mptt
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
    > 6916 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 4.2.0@afc3a47.
    > 
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader
    > '/usr/bin/composer' 'dump-autoload' '--classmap-authoritative' '--no-dev' '-vvv'

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104
Generating optimized autoload files (authoritative)
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
Generated optimized autoload files (authoritative) containing 2678 classes

PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Stack trace:
 /usr/share/php/JsonSchema/Constraints/Factory.php:195
 /usr/share/php/JsonSchema/Constraints/Constraint.php:116
 /usr/share/php/JsonSchema/Constraints/SchemaConstraint.php:92
 /usr/share/php/JsonSchema/Validator.php:63
 /usr/share/php/JsonSchema/Validator.php:78
 /usr/share/php/Composer/Json/JsonFile.php:192
 /usr/share/php/Composer/Factory.php:290
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Stack trace:
 /usr/share/php/JsonSchema/Constraints/Factory.php:195
 /usr/share/php/JsonSchema/Constraints/Constraint.php:116
 /usr/share/php/JsonSchema/Constraints/SchemaConstraint.php:92
 /usr/share/php/JsonSchema/Validator.php:63
 /usr/share/php/JsonSchema/Validator.php:78
 /usr/share/php/Composer/Json/JsonFile.php:192
 /usr/share/php/Composer/Factory.php:290
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/JsonSchema/Constraints/Constraint.php:48
Stack trace:
 /usr/share/php/JsonSchema/Constraints/Constraint.php:48
 /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:39
 /usr/share/php/JsonSchema/Constraints/Constraint.php:118
 /usr/share/php/JsonSchema/Constraints/SchemaConstraint.php:92
 /usr/share/php/JsonSchema/Validator.php:63
 /usr/share/php/JsonSchema/Validator.php:78
 /usr/share/php/Composer/Json/JsonFile.php:192
 /usr/share/php/Composer/Factory.php:290
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Reading ./composer.json
Loading config file /home/siva/.composer/config.json
Loading config file /home/siva/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Stack trace:
 /usr/share/php/Composer/Repository/WritableArrayRepository.php:22
 /usr/share/php/Composer/autoload.php:273
 /usr/share/php/Composer/Repository/FilesystemRepository.php:25
 /usr/share/php/Composer/autoload.php:273
 /usr/share/php/Composer/Repository/InstalledFilesystemRepository.php:20
 /usr/share/php/Composer/autoload.php:273
 /usr/share/php/Composer/Factory.php:429
 /usr/share/php/Composer/Factory.php:339
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Stack trace:
 /usr/share/php/Composer/Repository/FilesystemRepository.php:25
 /usr/share/php/Composer/autoload.php:273
 /usr/share/php/Composer/Repository/InstalledFilesystemRepository.php:20
 /usr/share/php/Composer/autoload.php:273
 /usr/share/php/Composer/Factory.php:429
 /usr/share/php/Composer/Factory.php:339
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/Repository/ArrayRepository.php:206
Stack trace:
 /usr/share/php/Composer/Factory.php:429
 /usr/share/php/Composer/Factory.php:339
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Executing command (/tmp/box/Box21228): git branch --no-color --no-abbrev -v
Deprecation Notice: Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Process/Process.php:606
Stack trace:
 /usr/share/php/Composer/Util/ProcessExecutor.php:68
 /usr/share/php/Composer/Package/Version/VersionGuesser.php:117
 /usr/share/php/Composer/Package/Version/VersionGuesser.php:67
 /usr/share/php/Composer/Package/Loader/RootPackageLoader.php:88
 /usr/share/php/Composer/Factory.php:351
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Executing command (/tmp/box/Box21228): git describe --exact-match --tags
Executing command (/tmp/box/Box21228): git log --pretty="%H" -n1 HEAD
Executing command (/tmp/box/Box21228): hg branch
Executing command (/tmp/box/Box21228): fossil branch list
Executing command (/tmp/box/Box21228): fossil tag list
Executing command (/tmp/box/Box21228): svn info --xml
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Stack trace:
 /usr/share/php/Composer/Repository/RepositoryFactory.php:107
 /usr/share/php/Composer/Package/Loader/RootPackageLoader.php:174
 /usr/share/php/Composer/Factory.php:351
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Stack trace:
 /usr/share/php/Composer/Repository/RepositoryFactory.php:107
 /usr/share/php/Composer/Package/Loader/RootPackageLoader.php:174
 /usr/share/php/Composer/Factory.php:351
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Failed to initialize global composer: Composer could not find the config file: /home/siva/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /tmp/box/Box21228/vendor/composer/installed.json
Deprecation Notice: Return type of Composer\DependencyResolver\Pool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Composer/DependencyResolver/Pool.php:166
Stack trace:
 /usr/share/php/Composer/Plugin/PluginManager.php:161
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Finder.php:620
Stack trace:
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:69
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Finder.php:691
Stack trace:
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:69
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/FileTypeFilterIterator.php:42
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:101
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:69
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php:81
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:745
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php:109
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:745
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/RecursiveDirectoryIterator.php:61
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:745
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php:55
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:748
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php:71
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:748
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php:76
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:748
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/FilenameFilterIterator.php:28
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:762
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Finder/Iterator/PathFilterIterator.php:27
Stack trace:
 /usr/share/php/Symfony/Component/Finder/Finder.php:782
 /usr/share/php/Symfony/Component/Finder/Finder.php:627
 /usr/share/php/Composer/Autoload/ClassMapGenerator.php:84
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:355
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:467
 /usr/share/php/Composer/Plugin/PluginManager.php:178
 /usr/share/php/Composer/Plugin/PluginManager.php:264
 /usr/share/php/Composer/Plugin/PluginManager.php:77
 /usr/share/php/Composer/Factory.php:384
 /usr/share/php/Composer/Factory.php:576
 /usr/share/php/Composer/Console/Application.php:368
 /usr/share/php/Composer/Console/Application.php:486
 /usr/share/php/Composer/Console/Application.php:178
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Loading plugin Pest\Plugin\Manager
Loading plugin PackageVersions\Installer
Running 1.10.1 (2020-03-13 20:34:27) with PHP 8.1.13 on Linux / 5.15.0-56-generic
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:322
Stack trace:
 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:96
 /usr/share/php/Composer/Autoload/AutoloadGenerator.php:322
 /usr/share/php/Composer/Command/DumpAutoloadCommand.php:78
 /usr/share/php/Symfony/Component/Console/Command/Command.php:255
 /usr/share/php/Symfony/Component/Console/Application.php:934
 /usr/share/php/Symfony/Component/Console/Application.php:273
 /usr/share/php/Composer/Console/Application.php:281
 /usr/share/php/Symfony/Component/Console/Application.php:149
 /usr/share/php/Composer/Console/Application.php:113
 /usr/bin/composer:62
Reading ./composer.lock

? Keep the Composer dump artefacts
? Compressing with the algorithm "GZ"
[debug] Increased the maximum number of open file descriptors from ("2176", "1048576") to ("7079", "unlimited")
    > Warning: the extension "zlib" will now be required to execute the PHAR
[debug] Restored the maximum number of open file descriptors
[debug] Restored the maximum number of open file descriptors
? Setting file permissions to 0755
* Done.

💡  1 recommendation found:
    - The "chmod" setting can be omitted since is set to its default value
No warning found.

 // PHAR: 6951 files (21.45MB)                                                                                          
 // You can inspect the generated PHAR with the "info" command.                                                         

 // Memory usage: 118.34MB (peak: 131.65MB), time: 13secs                                                               

[debug] Restarted process exited 0

**Comment by theofidry** [comment]
I'll check it out soonish, do you have a repo where I could test it out by any chance?

**Comment by glo45343** [comment]
I'm using  this repo https://github.com/laravel-zero/laravel-zero

**Comment by theofidry** [comment]
I have tried to reproduce it but could not with 4.4.0. If you still encounter the issue please open a new issue with a reproducer 🙏
