### ISSUE TITLE
Allow custom compactors

### ISSUE THREAD

**Issue by villfa** [box-project/box#727]
## Feature Request

As of today we can only use the compactors provided by Box.

I've learned this limitation by trying to add my own compactor.

So now I wonder what would be the best option:
- Allow Box users to define their own compactors
- Document this limitation explicitly, and maybe recommend to use other tools like Rector before building the phar

WDYT?

**Comment by theofidry** [comment]
I think adding custom compactors is tricky due to the dependencies of the compactors, at least not without non-trivial rework.

That said, I'm fine with adding more compactors to Box and also better documenting this limitation. But it's been a very long time if not the first time this was requested, out of curiosity what kind of compactor are you thinking about?

**Comment by villfa** [comment]
Here the compactor I wanted to test:
```php
<?php

declare(strict_types=1);

namespace My\Namespace;

use KevinGH\Box\Compactor\Compactor;

class StripDeclareStrictTypes implements Compactor
{
    public function compact(string $file, string $contents): string
    {
        return str_replace('declare(strict_types=1);', '', $contents);
    }
}
```

I thought, since my library is heavily tested with the strict_types mode activated in all files, keeping it active in the phar doesn't add much value, so I could remove it at built time and measure the impact on the performance.

**Comment by theofidry** [comment]
Could be experimented here I think, although not super big probably box is big enough to measure the diff?

Just in case, `box info` can be of help there too

**Comment by villfa** [comment]
I realised that could test it just with `find` + `sed` 😅
The results are disappointing though, even if I didn't have high hopes, the size went down from 609Kb to 607Kb, and there is no visible impact on the performance.

> I'm fine with adding more compactors to Box

Considering the results, I don't think it's worth adding this compactor.
