### ISSUE TITLE
Add the capability to check for system binaries in the requirements checker 

### ISSUE THREAD

**Issue by DAcodedBEAT** [box-project/box#866]
## Feature Request

Many PHP applications invoke system binaries at part of their business logic (either due to the lack of extensions or simplicity of using the known binary).

Since this is a common pattern, it might be nice to have the functionality to detect if required system binaries exist in the built-in Box requirements checker, similar to how the application currently checks for PHP versions and extensions required to execute your application.

Implementation considerations:

* different machines might have system binaries in different locations, so this should attempt to use the `$PATH` if an absolute path isn't provided
* different operating systems might use prefer different system binaries so when implementing, we might want to consider making the configuration schema optionally specify OS preference

**Comment by theofidry** [comment]
@DAcodedBEAT I might be able to take a look at this in a near future. Would have a concrete example/case that I could use as a basis?

**Comment by DAcodedBEAT** [comment]
> @DAcodedBEAT I might be able to take a look at this in a near future. Would have a concrete example/case that I could use as a basis?

Sure! At my previous employer, I built a developer experience CLI tool which required users to authenticate via OIDC.  As such, the tool had to start a http server, open a browser to a given auth page, and the auth page would redirect to the started http page on auth success to initiate the session.  To streamline this interaction, I had this tool automatically open the user's preferred browser via `open` on macOS, `explorer` on Windows, `xdg-open` on Linux, and `wslview` on Windows in WSL terminals.

In a simpler example, Composer makes use of `git` commands https://github.com/composer/composer/blob/main/src/Composer/Util/Git.php to pull given dependencies, and `git` can be installed anywhere on the host system (due to different package managers and operating systems installing it in different locations)

It would be nice if the requirements checker notify the user if the expected command(s) are missing.

**Comment by theofidry** [comment]
Hm ok then I am a bit more hesitant about this then.

The feature definitely has value and could greatly improve the UX, but I also feel like this is not Box's responsibility. The problem you describe, at its core, is to allow an app to check for system dependencies. Whilst it's more specific to CLI apps, it has nothing to do with PHARs (if the app is installed as a Composer package you are facing the same problem).

If the problem was easy to solve I would not mind much, as there is value in this feature, but it probably belongs more to a separate package and I don't think there is a ubiquitous way to check system dependencies either.

**Comment by DAcodedBEAT** [comment]
This doesn't necessarily have to be limited to CLI apps - I can see a scenario where a php web app exec's a system binary as part of its business logic.  In terms of how it is used, it's very similar to how php extensions are used, but the difference is that system binaries are not directly tied to the runtime.

If you don't want to add it to the requirements checker, how about adding the ability to layer in other PHARs before execution of the application (i.e. the ability to run 1 or more PHARs before the archived application, similar to how we currently have the requirements-checker)

**Comment by theofidry** [comment]
But the question is how would you do such checks and if they are not specific to CLI apps why would you not do it in the entry point of your app instead?

The requirement checker mechanism is done this way because it is very specific to PHARs, which bypasses Composer conflict resolution.

**Comment by DAcodedBEAT** [comment]
Ah, that's a fair point. Doing this in the application itself could also work :+1:

**Comment by theofidry** [comment]
Ok I'll close the issue then :)

The feature [checking the system dep] would be really nice to have though, definitely deserves a package on its own 👍
