### ISSUE TITLE
CompileTest expected OUTPUT outdated 

### ISSUE THREAD

**Issue by llaville** [box-project/box#928]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.3.7

Cosmetic fix, but will help to understand more about unit tests.

Run following command : `grep "Box version 3.x-dev@151e40a" tests/Console/Command/CompileTest.php`  (19 entries found)

**Comment by theofidry** [comment]
Maybe this should be changed for something more "test like". This piece of text is obsolete but it's not meant to be kept up to date neither. It's purely to have a stable output
