### ISSUE TITLE
Error in github action while publishing v4.3.8, missing assets in the release

### ISSUE THREAD

**Issue by sereinity** [box-project/box#944]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | v4.3.8 |
| PHP version | all |
| Platform with version | all |
| Github Repo | all |

The job https://github.com/box-project/box/actions/runs/4445812078 failed due to rate limit over github API.
Which prevented publishing the assets in the release https://github.com/box-project/box/releases/tag/4.3.8.

Could you publish the assets please?

Regards.

**Comment by theofidry** [comment]
I retries the job, should be fine now. Thanks for the report!
