### ISSUE TITLE
Advanced blacklist features

### ISSUE THREAD

**Issue by llaville** [box-project/box#946]
## Feature Request

Related to #96, the `blacklist` option is used as a directory filter.

With the configuration excerpt:

```json
{
    "blacklist": [
        "fixtures"
    ]
}
```
Contents of sub-directory `fixtures` are ignored.

But with the configuration excerpt:

```json
{
    "blacklist": [
        "vendor/humbug/box/fixtures"
    ]
}
```
When path is relative to the project source code,  contents of the folder are still included.

As there are no warning messages, we can consider that expected files were ignored but it's wrong and the final PHP Archive is bigger than expected !

**Comment by theofidry** [comment]
>As there are no warning messages, we can consider that expected files were ignored but it's wrong and the final PHP

You cannot fail/add warning for unmet blacklisted entries though: that would be the same as having a warning on git commit when an entry is in gitignore but not found.

>When path is relative to the project source code, contents of the folder are still included.

I really have no idea. I just remember spending dozen of hours to get the finder config tested and somewhat working when taking over box. The structure is there, but it's mostly the Symfony Finder magic underneath and I'm really not keen to work on this at all 😅 

I'll happily accept contributions there however, it should be relatively easy to add tests.
